"""Tests for scripts/docs_knowledge_check.py."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest
from scripts.docs_knowledge_check import (
    build_default_entry,
    discover_inventory_paths,
    inventory_sync,
    render_inventory_md,
    resolve_bundle_link,
    split_frontmatter,
    validate_inventory_schema,
)

ROOT = Path(__file__).resolve().parents[1]
INVENTORY_JSON = ROOT / "docs" / "knowledge" / "inventory.json"
INVENTORY_MD = ROOT / "docs" / "knowledge" / "inventory.md"
GENERATED_BANNER = "<!-- generated by scripts/docs_knowledge_check.py — do not edit -->"


def test_discover_inventory_paths_includes_root_surfaces() -> None:
    paths = discover_inventory_paths()
    assert "README.md" in paths
    assert "docs/ARCHITECTURE.md" in paths
    assert not any(path.startswith("docs/knowledge/") for path in paths)


def test_build_default_entry_marks_issue_bodies_as_artifact() -> None:
    entry = build_default_entry("docs/quality/issue-bodies/v2-phase0-prerequisites.md")
    assert entry["action"] == "artifact"
    assert entry["surface_class"] == "artifact"


def test_inventory_sync_preserves_curated_fields(tmp_path: Path) -> None:
    inventory_path = tmp_path / "inventory.json"
    payload = {
        "schema_version": 1,
        "scope": "repository-documentation",
        "entries": [
            {
                "path": "docs/ARCHITECTURE.md",
                "type": "Architecture",
                "title": "Curated title",
                "description": "Curated description",
                "status": "current",
                "audience": ["maintainer"],
                "surface_class": "concept-candidate",
                "canonical_for": "architecture.system",
                "owner": "core-runtime",
                "destination": "docs/knowledge/architecture/",
                "action": "split",
                "supersedes": [],
                "notes": "human curated",
            }
        ],
    }
    inventory_path.write_text(json.dumps(payload), encoding="utf-8")

    original_load = INVENTORY_JSON
    try:
        import scripts.docs_knowledge_check as module

        module.INVENTORY_JSON = inventory_path
        inventory_sync()
        data = json.loads(inventory_path.read_text(encoding="utf-8"))
    finally:
        import scripts.docs_knowledge_check as module

        module.INVENTORY_JSON = original_load

    arch = next(entry for entry in data["entries"] if entry["path"] == "docs/ARCHITECTURE.md")
    assert arch["title"] == "Curated title"
    assert arch["notes"] == "human curated"
    assert arch.get("missing") is False


def test_inventory_sync_marks_missing_without_deletion(tmp_path: Path) -> None:
    inventory_path = tmp_path / "inventory.json"
    payload = {
        "schema_version": 1,
        "scope": "repository-documentation",
        "entries": [
            {
                "path": "docs/DOES_NOT_EXIST.md",
                "type": "Archive",
                "title": "Gone",
                "description": "Missing file",
                "status": "archived",
                "audience": ["maintainer"],
                "surface_class": "concept-candidate",
                "canonical_for": None,
                "owner": "core-runtime",
                "destination": None,
                "action": "keep",
                "supersedes": [],
                "notes": "",
            }
        ],
    }
    inventory_path.write_text(json.dumps(payload), encoding="utf-8")

    import scripts.docs_knowledge_check as module

    original = module.INVENTORY_JSON
    module.INVENTORY_JSON = inventory_path
    try:
        inventory_sync()
        data = json.loads(inventory_path.read_text(encoding="utf-8"))
    finally:
        module.INVENTORY_JSON = original

    missing = next(entry for entry in data["entries"] if entry["path"] == "docs/DOES_NOT_EXIST.md")
    assert missing["missing"] is True
    assert len(data["entries"]) == len(discover_inventory_paths()) + 1


def test_render_inventory_md_is_byte_stable() -> None:
    data = json.loads(INVENTORY_JSON.read_text(encoding="utf-8"))
    first = render_inventory_md(data)
    second = render_inventory_md(data)
    assert first == second
    assert GENERATED_BANNER in first


def test_validate_inventory_schema_rejects_unsorted_paths() -> None:
    entry = {
        "type": "Archive",
        "title": "z",
        "description": "z",
        "status": "current",
        "action": "keep",
        "surface_class": "concept-candidate",
    }
    data = {
        "schema_version": 1,
        "scope": "repository-documentation",
        "entries": [
            {"path": "docs/z.md", **entry},
            {"path": "docs/a.md", **{**entry, "title": "a", "description": "a"}},
        ],
    }
    errors = validate_inventory_schema(data)
    assert any("sorted by path" in error for error in errors)


def test_resolve_bundle_link() -> None:
    target = resolve_bundle_link("/architecture/system-overview.md")
    assert target.name == "system-overview.md"


def test_split_frontmatter_parses_profile() -> None:
    meta, body = split_frontmatter(ROOT / "docs" / "knowledge" / "profile.md")
    assert meta is not None
    assert meta["type"] == "Specification"
    assert "Matryca knowledge profile" in body


def test_docs_check_script_exits_zero() -> None:
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "docs_knowledge_check.py"), "check-bundle"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr or result.stdout


def test_inventory_md_matches_generated_view() -> None:
    data = json.loads(INVENTORY_JSON.read_text(encoding="utf-8"))
    rendered = render_inventory_md(data)
    assert INVENTORY_MD.read_text(encoding="utf-8") == rendered


def test_inventory_probe_drift_gate_lifecycle(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Observation-phase gate: new legacy doc fails sync check until reconciled."""
    import scripts.docs_knowledge_check as module

    repo = tmp_path
    knowledge = repo / "docs" / "knowledge"
    knowledge.mkdir(parents=True)
    (repo / "docs" / "existing.md").write_text("# Existing\n\nBaseline doc.\n", encoding="utf-8")

    inventory_path = knowledge / "inventory.json"
    inventory_md_path = knowledge / "inventory.md"
    baseline_entry = build_default_entry("docs/existing.md")
    payload = {
        "schema_version": 1,
        "scope": "repository-documentation",
        "entries": [baseline_entry],
    }
    inventory_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    inventory_md_path.write_text(render_inventory_md(payload), encoding="utf-8")

    monkeypatch.setattr(module, "ROOT", repo)
    monkeypatch.setattr(module, "KNOWLEDGE_DIR", knowledge)
    monkeypatch.setattr(module, "INVENTORY_JSON", inventory_path)
    monkeypatch.setattr(module, "INVENTORY_MD", inventory_md_path)
    monkeypatch.setattr(module, "ROOT_SURFACE_PATHS", ())

    module.inventory_sync(check=True)

    probe_path = repo / "docs" / "_inventory_probe.md"
    probe_path.write_text("# Inventory probe\n\nTemporary observation fixture.\n", encoding="utf-8")

    with pytest.raises(SystemExit) as drift_exc:
        module.inventory_sync(check=True)
    assert drift_exc.value.code == 1

    module.inventory_sync()
    module.inventory_md()
    module.inventory_md(check=True)

    reconciled = json.loads(inventory_path.read_text(encoding="utf-8"))
    probe_entry = next(
        entry for entry in reconciled["entries"] if entry["path"] == "docs/_inventory_probe.md"
    )
    assert probe_entry.get("missing") is not True
    assert probe_entry["title"] == "Inventory probe"

    module.inventory_sync(check=True)
