"""Tests for scripts/docs_knowledge_check.py."""

from __future__ import annotations

import json
import subprocess
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import pytest
from scripts.docs_knowledge_check import (
    KNOWLEDGE_DIR,
    build_default_entry,
    discover_inventory_paths,
    inventory_sync,
    migrate_inventory_schema,
    render_inventory_md,
    resolve_bundle_link,
    resolve_legacy_source,
    split_frontmatter,
    validate_concept_frontmatter,
    validate_document_links,
    validate_inventory_schema,
    validate_legacy_sources,
)

ROOT = Path(__file__).resolve().parents[1]
INVENTORY_JSON = ROOT / "docs" / "knowledge" / "inventory.json"
INVENTORY_MD = ROOT / "docs" / "knowledge" / "inventory.md"
GENERATED_BANNER = "<!-- generated by scripts/docs_knowledge_check.py — do not edit -->"


def test_discover_inventory_paths_includes_root_surfaces() -> None:
    paths = discover_inventory_paths()
    assert "README.md" in paths
    assert "docs/ARCHITECTURE.md" in paths
    assert not any(path.startswith("docs/knowledge/") for path in paths)


def test_build_default_entry_marks_issue_bodies_as_artifact() -> None:
    entry = build_default_entry("docs/quality/issue-bodies/v2-phase0-prerequisites.md")
    assert entry["action"] == "artifact"
    assert entry["surface_class"] == "artifact"


def test_inventory_sync_preserves_curated_fields(tmp_path: Path) -> None:
    inventory_path = tmp_path / "inventory.json"
    payload = {
        "schema_version": 2,
        "scope": "repository-documentation",
        "entries": [
            {
                "path": "docs/ARCHITECTURE.md",
                "type": "Architecture",
                "title": "Curated title",
                "description": "Curated description",
                "classification": "canonical",
                "audience": ["maintainer"],
                "surface_class": "concept-candidate",
                "canonical_for": "architecture.system",
                "owner": "core-runtime",
                "destination": "docs/knowledge/architecture/",
                "action": "split",
                "supersedes": [],
                "notes": "human curated",
            }
        ],
    }
    inventory_path.write_text(json.dumps(payload), encoding="utf-8")

    original_load = INVENTORY_JSON
    try:
        import scripts.docs_knowledge_check as module

        module.INVENTORY_JSON = inventory_path
        inventory_sync()
        data = json.loads(inventory_path.read_text(encoding="utf-8"))
    finally:
        import scripts.docs_knowledge_check as module

        module.INVENTORY_JSON = original_load

    arch = next(entry for entry in data["entries"] if entry["path"] == "docs/ARCHITECTURE.md")
    assert arch["title"] == "Curated title"
    assert arch["notes"] == "human curated"
    assert arch.get("missing") is False


def test_inventory_sync_marks_missing_without_deletion(tmp_path: Path) -> None:
    inventory_path = tmp_path / "inventory.json"
    payload = {
        "schema_version": 2,
        "scope": "repository-documentation",
        "entries": [
            {
                "path": "docs/DOES_NOT_EXIST.md",
                "type": "Archive",
                "title": "Gone",
                "description": "Missing file",
                "classification": "historical",
                "audience": ["maintainer"],
                "surface_class": "concept-candidate",
                "canonical_for": None,
                "owner": "core-runtime",
                "destination": None,
                "action": "keep",
                "supersedes": [],
                "notes": "",
            }
        ],
    }
    inventory_path.write_text(json.dumps(payload), encoding="utf-8")

    import scripts.docs_knowledge_check as module

    original = module.INVENTORY_JSON
    module.INVENTORY_JSON = inventory_path
    try:
        inventory_sync()
        data = json.loads(inventory_path.read_text(encoding="utf-8"))
    finally:
        module.INVENTORY_JSON = original

    missing = next(entry for entry in data["entries"] if entry["path"] == "docs/DOES_NOT_EXIST.md")
    assert missing["missing"] is True
    assert len(data["entries"]) == len(discover_inventory_paths()) + 1


def test_render_inventory_md_is_byte_stable() -> None:
    data = json.loads(INVENTORY_JSON.read_text(encoding="utf-8"))
    first = render_inventory_md(data)
    second = render_inventory_md(data)
    assert first == second
    assert GENERATED_BANNER in first


def test_validate_inventory_schema_rejects_unsorted_paths() -> None:
    entry = {
        "type": "Archive",
        "title": "z",
        "description": "z",
        "classification": "active",
        "action": "keep",
        "surface_class": "concept-candidate",
    }
    data = {
        "schema_version": 2,
        "scope": "repository-documentation",
        "entries": [
            {"path": "docs/z.md", **entry},
            {"path": "docs/a.md", **{**entry, "title": "a", "description": "a"}},
        ],
    }
    errors = validate_inventory_schema(data)
    assert any("sorted by path" in error for error in errors)


def test_validate_inventory_schema_rejects_duplicate_canonical_roles() -> None:
    common = {
        "type": "Architecture",
        "title": "Architecture",
        "description": "Architecture contract.",
        "classification": "canonical",
        "canonical_for": "architecture.system",
        "action": "keep",
        "surface_class": "concept-candidate",
    }
    data = {
        "schema_version": 2,
        "scope": "repository-documentation",
        "entries": [
            {"path": "docs/a.md", **common},
            {"path": "docs/b.md", **common},
        ],
    }

    errors = validate_inventory_schema(data)

    assert any("duplicate inventory canonical_for" in error for error in errors)


def test_resolve_bundle_link() -> None:
    target = resolve_bundle_link("/architecture/system-overview.md")
    assert target.name == "system-overview.md"


def test_migrate_inventory_schema_separates_classification() -> None:
    data: dict[str, Any] = {
        "schema_version": 1,
        "scope": "repository-documentation",
        "entries": [
            {"path": "docs/history.md", "status": "archived", "action": "archive"},
            {
                "path": "docs/ARCHITECTURE.md",
                "status": "current",
                "action": "split",
                "canonical_for": "architecture.system",
            },
            {"path": "CHANGELOG.md", "status": "current", "action": "generated"},
        ],
    }

    assert migrate_inventory_schema(data) is True
    assert data["schema_version"] == 2
    entries = data["entries"]
    assert isinstance(entries, list)
    assert [entry["classification"] for entry in entries] == [
        "historical",
        "canonical",
        "generated",
    ]
    assert all("status" not in entry for entry in entries)


def test_split_frontmatter_parses_profile() -> None:
    meta, body = split_frontmatter(ROOT / "docs" / "knowledge" / "profile.md")
    assert meta is not None
    assert meta["type"] == "Specification"
    assert "Matryca Plumber knowledge profile" in body


def test_docs_check_script_exits_zero() -> None:
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "docs_knowledge_check.py"), "check-bundle"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr or result.stdout


def test_inventory_md_matches_generated_view() -> None:
    data = json.loads(INVENTORY_JSON.read_text(encoding="utf-8"))
    rendered = render_inventory_md(data)
    assert INVENTORY_MD.read_text(encoding="utf-8") == rendered


def test_inventory_probe_drift_gate_lifecycle(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Observation-phase gate: new legacy doc fails sync check until reconciled."""
    import scripts.docs_knowledge_check as module

    repo = tmp_path
    knowledge = repo / "docs" / "knowledge"
    knowledge.mkdir(parents=True)
    (repo / "docs" / "existing.md").write_text("# Existing\n\nBaseline doc.\n", encoding="utf-8")

    inventory_path = knowledge / "inventory.json"
    inventory_md_path = knowledge / "inventory.md"
    baseline_entry = build_default_entry("docs/existing.md")
    payload = {
        "schema_version": 1,
        "scope": "repository-documentation",
        "entries": [baseline_entry],
    }
    inventory_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    inventory_md_path.write_text(render_inventory_md(payload), encoding="utf-8")

    monkeypatch.setattr(module, "ROOT", repo)
    monkeypatch.setattr(module, "KNOWLEDGE_DIR", knowledge)
    monkeypatch.setattr(module, "INVENTORY_JSON", inventory_path)
    monkeypatch.setattr(module, "INVENTORY_MD", inventory_md_path)
    monkeypatch.setattr(module, "ROOT_SURFACE_PATHS", ())

    module.inventory_sync(check=True)

    probe_path = repo / "docs" / "_inventory_probe.md"
    probe_path.write_text("# Inventory probe\n\nTemporary observation fixture.\n", encoding="utf-8")

    with pytest.raises(SystemExit) as drift_exc:
        module.inventory_sync(check=True)
    assert drift_exc.value.code == 1

    module.inventory_sync()
    module.inventory_md()
    module.inventory_md(check=True)

    reconciled = json.loads(inventory_path.read_text(encoding="utf-8"))
    probe_entry = next(
        entry for entry in reconciled["entries"] if entry["path"] == "docs/_inventory_probe.md"
    )
    assert probe_entry.get("missing") is not True
    assert probe_entry["title"] == "Inventory probe"

    module.inventory_sync(check=True)


ARCHITECTURE_PILOTS = (
    "architecture/system-overview.md",
    "architecture/graph-plane.md",
    "architecture/shadow-db.md",
)


def test_resolve_legacy_source_valid_llms_txt() -> None:
    concept = KNOWLEDGE_DIR / "architecture" / "shadow-db.md"
    resolved = resolve_legacy_source("../../../llms.txt", concept)
    assert resolved == (ROOT / "llms.txt").resolve()
    assert resolved.is_file()


def test_resolve_legacy_source_rejects_absolute_path() -> None:
    concept = KNOWLEDGE_DIR / "architecture" / "shadow-db.md"
    with pytest.raises(ValueError, match="repo-relative"):
        resolve_legacy_source("/etc/passwd", concept)


def test_resolve_legacy_source_rejects_escape_outside_repo(tmp_path: Path) -> None:
    concept = tmp_path / "docs" / "knowledge" / "architecture" / "pilot.md"
    concept.parent.mkdir(parents=True)
    with pytest.raises(ValueError, match="inside repository root"):
        resolve_legacy_source("../../../../outside.md", concept)


def test_validate_legacy_sources_missing_file() -> None:
    concept = KNOWLEDGE_DIR / "architecture" / "graph-plane.md"
    errors = validate_legacy_sources(
        {"legacy_sources": ["../../DOES_NOT_EXIST.md"]},
        concept,
        "architecture/graph-plane.md",
    )
    assert any("missing legacy_sources" in error for error in errors)


def test_validate_legacy_sources_rejects_absolute() -> None:
    concept = KNOWLEDGE_DIR / "architecture" / "graph-plane.md"
    errors = validate_legacy_sources(
        {"legacy_sources": ["/tmp/secret.md"]},
        concept,
        "architecture/graph-plane.md",
    )
    assert any("repo-relative" in error for error in errors)


def test_architecture_pilot_frontmatter_required_fields() -> None:
    required = (
        "type",
        "title",
        "description",
        "tags",
        "generated",
        "verified",
        "last_verified",
        "stale_after",
        "status",
        "classification",
        "canonical_for",
        "audience",
        "owner",
    )
    for rel in ARCHITECTURE_PILOTS:
        meta, _ = split_frontmatter(KNOWLEDGE_DIR / rel)
        assert meta is not None, rel
        for field in required:
            assert field in meta, f"{rel} missing {field}"
        assert meta["type"] == "Architecture"
        assert meta["status"] == "stable"
        assert meta["classification"] == "canonical"


def test_validate_concept_frontmatter_rejects_legacy_status() -> None:
    path = KNOWLEDGE_DIR / "architecture" / "system-overview.md"
    meta, _ = split_frontmatter(path)
    assert meta is not None
    changed = dict(meta)
    changed["status"] = "experimental"

    errors = validate_concept_frontmatter(path, changed)

    assert any("invalid OKF status" in error for error in errors)


def test_validate_concept_frontmatter_rejects_empty_verification() -> None:
    path = KNOWLEDGE_DIR / "architecture" / "system-overview.md"
    meta, _ = split_frontmatter(path)
    assert meta is not None
    changed = dict(meta)
    changed["verified"] = []

    errors = validate_concept_frontmatter(path, changed)

    assert any("at least one verification event" in error for error in errors)


def test_validate_concept_frontmatter_rejects_inconsistent_freshness() -> None:
    path = KNOWLEDGE_DIR / "architecture" / "system-overview.md"
    meta, _ = split_frontmatter(path)
    assert meta is not None
    changed = dict(meta)
    changed["last_verified"] = "2026-08-05"
    changed["stale_after"] = "2026-08-05"

    errors = validate_concept_frontmatter(path, changed)

    assert any("stale_after must be after last_verified" in error for error in errors)
    assert any("latest verified event date" in error for error in errors)


def test_validate_document_links_rejects_missing_anchor(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import scripts.docs_knowledge_check as module

    monkeypatch.setattr(module, "ROOT", tmp_path)
    source = tmp_path / "source.md"
    target = tmp_path / "target.md"
    source.write_text("[Missing](target.md#absent)\n", encoding="utf-8")
    target.write_text("# Present\n", encoding="utf-8")

    errors = validate_document_links(source, source.read_text(encoding="utf-8"), "source.md")

    assert any("broken local anchor" in error for error in errors)


def test_shadow_db_since_version() -> None:
    meta, _ = split_frontmatter(KNOWLEDGE_DIR / "architecture" / "shadow-db.md")
    assert meta is not None
    assert meta.get("since") == "v2.0.0-alpha"
    assert meta.get("since") != "v2.0.0-alpha.1"


def test_architecture_pilot_related_reciprocal() -> None:
    concepts: dict[str, set[str]] = {}
    for rel in ARCHITECTURE_PILOTS:
        meta, _ = split_frontmatter(KNOWLEDGE_DIR / rel)
        assert meta is not None
        related = meta.get("related", [])
        assert isinstance(related, list)
        concepts[rel] = {item for item in related if isinstance(item, str)}

    overview = "architecture/system-overview.md"
    graph = "architecture/graph-plane.md"
    shadow = "architecture/shadow-db.md"

    assert f"/{overview}" in concepts[graph]
    assert f"/{graph}" in concepts[overview]
    assert f"/{shadow}" in concepts[overview]
    assert f"/{overview}" in concepts[shadow]
    assert f"/{graph}" in concepts[shadow]
    assert f"/{shadow}" in concepts[graph]


def test_check_bundle_passes_concept_rel_to_validate_legacy_sources(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Regression: check_bundle must pass concept rel, not an undefined label."""
    import scripts.docs_knowledge_check as module

    captured: list[str] = []

    def spy(meta: Mapping[str, Any], concept_path: Path, label: str) -> list[str]:
        captured.append(label)
        return validate_legacy_sources(meta, concept_path, label)

    monkeypatch.setattr(module, "validate_legacy_sources", spy)
    module.check_bundle()
    assert captured, "expected validate_legacy_sources to run for pilot concepts"
    assert "architecture/shadow-db.md" in captured
    assert "architecture/graph-plane.md" in captured
    assert all(isinstance(label, str) and label for label in captured)
