#!/usr/bin/env python3
"""OKF-inspired knowledge bundle checks, inventory sync, and legacy audit."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, cast

import yaml

ROOT = Path(__file__).resolve().parents[1]
KNOWLEDGE_DIR = ROOT / "docs" / "knowledge"
INVENTORY_JSON = KNOWLEDGE_DIR / "inventory.json"
INVENTORY_MD = KNOWLEDGE_DIR / "inventory.md"
PROFILE_MD = KNOWLEDGE_DIR / "profile.md"

GENERATED_BANNER = "<!-- generated by scripts/docs_knowledge_check.py — do not edit -->"

DOC_TYPES: frozenset[str] = frozenset(
    {
        "Product Overview",
        "Guide",
        "Architecture",
        "Specification",
        "Reference",
        "Runbook",
        "Decision",
        "Roadmap",
        "Audit",
        "Release Note",
        "Archive",
    }
)

STATUSES: frozenset[str] = frozenset(
    {"current", "experimental", "planned", "deprecated", "archived"}
)

ACTIONS: frozenset[str] = frozenset(
    {"keep", "migrate", "split", "merge", "archive", "artifact", "generated"}
)

SURFACE_CLASSES: frozenset[str] = frozenset(
    {
        "concept-candidate",
        "runtime-contract",
        "repository-entrypoint",
        "generated",
        "artifact",
    }
)

AUDIENCES: frozenset[str] = frozenset({"maintainer", "contributor", "operator", "agent"})

ROOT_SURFACE_PATHS: tuple[str, ...] = (
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "SUPPORT.md",
    "AGENTS.md",
    "llms.txt",
    ".well-known/llms.txt",
    "SYSTEM_PROMPT.md",
    "ROADMAP.md",
    "CHANGELOG.md",
    "PROJECT_DIARY.md",
)

INDEX_EXCEPTIONS: frozenset[str] = frozenset({"index.md"})

CURATED_ENTRY_FIELDS: frozenset[str] = frozenset(
    {
        "path",
        "type",
        "title",
        "description",
        "status",
        "audience",
        "surface_class",
        "canonical_for",
        "owner",
        "destination",
        "action",
        "supersedes",
        "notes",
        "missing",
    }
)


@dataclass(frozen=True)
class HeuristicDefaults:
    doc_type: str
    action: str
    surface_class: str
    destination: str | None = None


def _fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def _repo_rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        msg = "missing YAML frontmatter opener"
        raise ValueError(msg)
    end = text.find("\n---\n", 4)
    if end == -1:
        msg = "missing YAML frontmatter closer"
        raise ValueError(msg)
    raw = text[4:end]
    body = text[end + 5 :]
    data = yaml.safe_load(raw)
    if not isinstance(data, dict):
        msg = "frontmatter must be a mapping"
        raise ValueError(msg)
    return data, body


def split_frontmatter(path: Path) -> tuple[dict[str, Any] | None, str]:
    text = _read_text(path)
    if not text.startswith("---\n"):
        return None, text
    try:
        meta, body = parse_frontmatter(text)
    except ValueError:
        return None, text
    return meta, body


def _first_heading_title(text: str) -> str | None:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def _first_sentence(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("```"):
            continue
        sentence = re.split(r"(?<=[.!?])\s+", stripped, maxsplit=1)[0].strip()
        if sentence:
            return sentence
    return ""


def _default_owner(path: str) -> str:
    if path.startswith("docs/openspec/agent"):
        return "prompt-runtime"
    if path.startswith("docs/roadmaps/"):
        return "planning"
    if path.startswith("docs/releases/"):
        return "release"
    if path.startswith("docs/quality/"):
        return "quality"
    return "core-runtime"


def _heuristic_defaults(path: str) -> HeuristicDefaults:
    if path in ROOT_SURFACE_PATHS:
        if path in {"SYSTEM_PROMPT.md", "llms.txt", ".well-known/llms.txt"}:
            return HeuristicDefaults(
                "Reference",
                "generated",
                "generated",
                None,
            )
        if path == "CHANGELOG.md":
            return HeuristicDefaults(
                "Release Note",
                "generated",
                "generated",
                None,
            )
        if path == "PROJECT_DIARY.md":
            return HeuristicDefaults(
                "Decision",
                "split",
                "repository-entrypoint",
                "docs/knowledge/decisions/",
            )
        return HeuristicDefaults(
            "Reference",
            "keep",
            "repository-entrypoint",
            None,
        )
    if path.startswith("docs/releases/"):
        return HeuristicDefaults(
            "Release Note",
            "archive",
            "concept-candidate",
            "docs/knowledge/releases/",
        )
    if path.startswith("docs/quality/issue-bodies/"):
        return HeuristicDefaults("Archive", "artifact", "artifact", "docs/artifacts/issue-bodies/")
    if path.startswith("docs/roadmaps/"):
        return HeuristicDefaults(
            "Roadmap",
            "migrate",
            "concept-candidate",
            "docs/knowledge/roadmaps/active/",
        )
    if path.startswith("docs/openspec/"):
        return HeuristicDefaults(
            "Specification",
            "migrate",
            "concept-candidate",
            "docs/knowledge/specifications/",
        )
    if path.startswith("docs/v1.8-"):
        return HeuristicDefaults("Archive", "archive", "concept-candidate", "docs/archive/plans/")
    if path.startswith("docs/AUDIT_"):
        return HeuristicDefaults(
            "Audit",
            "archive",
            "concept-candidate",
            "docs/knowledge/quality/audits/",
        )
    if path == "docs/ARCHITECTURE.md":
        return HeuristicDefaults(
            "Architecture",
            "split",
            "concept-candidate",
            "docs/knowledge/architecture/",
        )
    if path == "docs/PROJECT_DIARY.md":
        return HeuristicDefaults(
            "Decision",
            "split",
            "concept-candidate",
            "docs/knowledge/decisions/",
        )
    if path.startswith("docs/quality/"):
        return HeuristicDefaults("Audit", "archive", "concept-candidate", "docs/knowledge/quality/")
    if path.startswith("docs/integrations/"):
        return HeuristicDefaults("Guide", "migrate", "concept-candidate", "docs/knowledge/guides/")
    return HeuristicDefaults("Archive", "keep", "concept-candidate", None)


def _default_audience(path: str) -> list[str]:
    if path in {"llms.txt", ".well-known/llms.txt", "SYSTEM_PROMPT.md"}:
        return ["agent", "operator"]
    if path in {"README.md", "CONTRIBUTING.md"}:
        return ["contributor", "operator"]
    if path.startswith("docs/openspec/agent"):
        return ["agent", "maintainer"]
    return ["maintainer", "contributor"]


def _default_status(path: str, action: str) -> str:
    if action in {"artifact", "archive"}:
        return "archived"
    if path.startswith("docs/roadmaps/"):
        return "planned"
    return "current"


def discover_inventory_paths() -> list[str]:
    paths: set[str] = set(ROOT_SURFACE_PATHS)
    docs_root = ROOT / "docs"
    for path in sorted(docs_root.rglob("*.md")):
        rel = _repo_rel(path)
        if rel.startswith("docs/knowledge/"):
            continue
        paths.add(rel)
    return sorted(paths)


def build_default_entry(path: str) -> dict[str, Any]:
    file_path = ROOT / path
    text = _read_text(file_path) if file_path.is_file() else ""
    title = _first_heading_title(text) or path
    description = _first_sentence(text) or f"Documentation file at {path}."
    defaults = _heuristic_defaults(path)
    status = _default_status(path, defaults.action)
    entry: dict[str, Any] = {
        "path": path,
        "type": defaults.doc_type,
        "title": title,
        "description": description,
        "status": status,
        "audience": _default_audience(path),
        "surface_class": defaults.surface_class,
        "canonical_for": None,
        "owner": _default_owner(path),
        "destination": defaults.destination,
        "action": defaults.action,
        "supersedes": [],
        "notes": "",
    }
    if path == "docs/ARCHITECTURE.md":
        entry["canonical_for"] = "architecture.system"
    return entry


def load_inventory() -> dict[str, Any]:
    if not INVENTORY_JSON.is_file():
        _fail(f"missing inventory: {INVENTORY_JSON.relative_to(ROOT)}")
    parsed: object = json.loads(_read_text(INVENTORY_JSON))
    if not isinstance(parsed, dict):
        _fail("inventory.json root must be an object")
    return cast(dict[str, Any], parsed)


def validate_inventory_schema(data: Mapping[str, Any]) -> list[str]:
    errors: list[str] = []
    if data.get("schema_version") != 1:
        errors.append("inventory.json schema_version must be 1")
    if data.get("scope") != "repository-documentation":
        errors.append("inventory.json scope must be 'repository-documentation'")
    entries = data.get("entries")
    if not isinstance(entries, list):
        errors.append("inventory.json entries must be a list")
        return errors

    seen_paths: set[str] = set()
    for index, entry in enumerate(entries):
        prefix = f"entries[{index}]"
        if not isinstance(entry, dict):
            errors.append(f"{prefix} must be an object")
            continue
        path = entry.get("path")
        if not isinstance(path, str) or not path:
            errors.append(f"{prefix}.path must be a non-empty string")
            continue
        if path in seen_paths:
            errors.append(f"duplicate inventory path: {path}")
        seen_paths.add(path)
        for field in ("type", "title", "description", "status", "action", "surface_class"):
            if field not in entry:
                errors.append(f"{prefix}.{field} is required")
        doc_type = entry.get("type")
        if isinstance(doc_type, str) and doc_type not in DOC_TYPES:
            errors.append(f"{prefix}.type invalid: {doc_type}")
        status = entry.get("status")
        if isinstance(status, str) and status not in STATUSES:
            errors.append(f"{prefix}.status invalid: {status}")
        action = entry.get("action")
        if isinstance(action, str) and action not in ACTIONS:
            errors.append(f"{prefix}.action invalid: {action}")
        surface_class = entry.get("surface_class")
        if isinstance(surface_class, str) and surface_class not in SURFACE_CLASSES:
            errors.append(f"{prefix}.surface_class invalid: {surface_class}")
        audience = entry.get("audience")
        if audience is not None and (
            not isinstance(audience, list)
            or not all(isinstance(item, str) and item in AUDIENCES for item in audience)
        ):
            errors.append(f"{prefix}.audience must be a list of known audience values")
        destination = entry.get("destination")
        if destination is not None and not isinstance(destination, str):
            errors.append(f"{prefix}.destination must be a string or null")
        canonical_for = entry.get("canonical_for")
        if canonical_for is not None and not isinstance(canonical_for, str):
            errors.append(f"{prefix}.canonical_for must be a string or null")

    sorted_paths = [
        entry["path"] for entry in entries if isinstance(entry, dict) and "path" in entry
    ]
    if sorted_paths != sorted(sorted_paths):
        errors.append("inventory.json entries must be sorted by path")
    return errors


def inventory_init(*, force: bool = False) -> None:
    if INVENTORY_JSON.exists() and not force:
        _fail(
            f"{INVENTORY_JSON.relative_to(ROOT)} already exists; "
            "use inventory-sync or --force to overwrite"
        )
    entries = [build_default_entry(path) for path in discover_inventory_paths()]
    payload = {
        "schema_version": 1,
        "scope": "repository-documentation",
        "entries": entries,
    }
    INVENTORY_JSON.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY_JSON.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"inventory initialized: {len(entries)} entries")


def inventory_sync(*, check: bool = False) -> None:
    data = load_inventory()
    existing_entries = data.get("entries", [])
    if not isinstance(existing_entries, list):
        _fail("inventory.json entries must be a list")

    by_path: dict[str, dict[str, Any]] = {}
    for entry in existing_entries:
        if isinstance(entry, dict) and isinstance(entry.get("path"), str):
            by_path[entry["path"]] = dict(entry)

    discovered = discover_inventory_paths()
    discovered_set = set(discovered)
    new_paths = [path for path in discovered if path not in by_path]
    missing_paths = [
        path for path in by_path if path not in discovered_set and not by_path[path].get("missing")
    ]

    if check:
        if new_paths or missing_paths:
            details: list[str] = []
            if new_paths:
                details.append(f"new paths ({len(new_paths)}): {', '.join(new_paths[:5])}")
            if missing_paths:
                details.append(
                    f"missing paths ({len(missing_paths)}): {', '.join(missing_paths[:5])}"
                )
            _fail("inventory drift detected; run make docs-inventory-sync — " + "; ".join(details))
        print("inventory sync OK (no drift)")
        return

    for path in discovered:
        if path not in by_path:
            by_path[path] = build_default_entry(path)
        else:
            by_path[path]["missing"] = False

    for path, entry in by_path.items():
        if path not in discovered_set:
            entry["missing"] = True

    merged_entries = [by_path[path] for path in sorted(by_path)]
    data["entries"] = merged_entries
    INVENTORY_JSON.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(
        f"inventory synced: {len(new_paths)} added, {len(missing_paths)} marked missing, "
        f"{len(merged_entries)} total"
    )


def render_inventory_md(data: Mapping[str, Any]) -> str:
    entries = data.get("entries", [])
    if not isinstance(entries, list):
        _fail("inventory.json entries must be a list")

    lines = [
        "---",
        "type: Reference",
        "title: Repository documentation inventory",
        "description: Generated view of curated documentation inventory entries.",
        "timestamp: 2026-07-18T00:00:00Z",
        "status: experimental",
        "audience: [maintainer, agent]",
        "owner: core-runtime",
        "supersedes: []",
        "related: []",
        "---",
        "",
        GENERATED_BANNER,
        "",
        "# Repository documentation inventory",
        "",
        "Generated from [`inventory.json`](inventory.json). Do not edit this file by hand.",
        "",
    ]

    grouped: dict[str, list[dict[str, Any]]] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        action = str(entry.get("action", "keep"))
        grouped.setdefault(action, []).append(entry)

    for action in sorted(grouped):
        lines.append(f"## {action}")
        lines.append("")
        lines.append("| path | type | status | destination | canonical_for | missing |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for entry in sorted(grouped[action], key=lambda item: str(item.get("path", ""))):
            path = str(entry.get("path", ""))
            doc_type = str(entry.get("type", ""))
            status = str(entry.get("status", ""))
            destination = entry.get("destination") or ""
            canonical_for = entry.get("canonical_for") or ""
            missing = "yes" if entry.get("missing") else ""
            lines.append(
                "| "
                f"`{path}` | {doc_type} | {status} | {destination} | "
                f"{canonical_for} | {missing} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def inventory_md(*, check: bool = False) -> None:
    data = load_inventory()
    rendered = render_inventory_md(data)
    if check:
        if not INVENTORY_MD.is_file():
            _fail(f"missing generated inventory view: {INVENTORY_MD.relative_to(ROOT)}")
        if _read_text(INVENTORY_MD) != rendered:
            _fail("inventory.md drift; run make docs-inventory-md")
        print("inventory.md OK")
        return
    INVENTORY_MD.write_text(rendered, encoding="utf-8")
    print(f"wrote {INVENTORY_MD.relative_to(ROOT)}")


def _validate_timestamp(value: Any, label: str) -> list[str]:
    if isinstance(value, datetime):
        return []
    if not isinstance(value, str):
        return [f"{label} must be an ISO 8601 string or datetime"]
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return [f"{label} must be an ISO 8601 timestamp"]
    return []


def _bundle_link_targets(body: str) -> list[str]:
    return re.findall(r"\]\((/[^)]+)\)", body)


def resolve_bundle_link(target: str) -> Path:
    clean = target.split("#", 1)[0]
    if not clean.startswith("/"):
        msg = f"bundle link must start with /: {target}"
        raise ValueError(msg)
    return KNOWLEDGE_DIR / clean.lstrip("/")


def validate_concept_frontmatter(path: Path, meta: Mapping[str, Any]) -> list[str]:
    errors: list[str] = []
    rel = path.relative_to(KNOWLEDGE_DIR).as_posix()
    label = f"{rel}"

    doc_type = meta.get("type")
    if not isinstance(doc_type, str) or doc_type not in DOC_TYPES:
        errors.append(f"{label}: type must be one of profile types")

    for field in ("title", "description", "timestamp"):
        if field not in meta:
            errors.append(f"{label}: missing required field {field}")

    status = meta.get("status")
    if status is not None and (not isinstance(status, str) or status not in STATUSES):
        errors.append(f"{label}: invalid status")

    audience = meta.get("audience")
    if audience is not None and (
        not isinstance(audience, list)
        or not all(isinstance(item, str) and item in AUDIENCES for item in audience)
    ):
        errors.append(f"{label}: invalid audience")

    errors.extend(_validate_timestamp(meta.get("timestamp"), f"{label}.timestamp"))
    return errors


def collect_knowledge_concepts() -> list[Path]:
    concepts: list[Path] = []
    for path in sorted(KNOWLEDGE_DIR.rglob("*.md")):
        rel = path.relative_to(KNOWLEDGE_DIR).as_posix()
        if rel in INDEX_EXCEPTIONS or rel.endswith("/index.md"):
            continue
        concepts.append(path)
    return concepts


def check_bundle() -> None:
    errors: list[str] = []

    if not PROFILE_MD.is_file():
        errors.append("missing docs/knowledge/profile.md")

    data = load_inventory()
    errors.extend(validate_inventory_schema(data))

    canonical_for_values: dict[str, str] = {}
    for concept_path in collect_knowledge_concepts():
        rel = concept_path.relative_to(KNOWLEDGE_DIR).as_posix()
        meta, body = split_frontmatter(concept_path)
        if meta is None:
            errors.append(f"{rel}: concept documents require YAML frontmatter")
            continue
        errors.extend(validate_concept_frontmatter(concept_path, meta))

        canonical_for = meta.get("canonical_for")
        if canonical_for is not None:
            if not isinstance(canonical_for, str):
                errors.append(f"{rel}: canonical_for must be a string")
            elif canonical_for in canonical_for_values:
                errors.append(
                    f"duplicate canonical_for {canonical_for!r} in "
                    f"{canonical_for_values[canonical_for]} and {rel}"
                )
            else:
                canonical_for_values[canonical_for] = rel

        for target in _bundle_link_targets(body):
            try:
                resolved = resolve_bundle_link(target)
            except ValueError as exc:
                errors.append(f"{rel}: {exc}")
                continue
            if not resolved.is_file():
                errors.append(f"{rel}: broken bundle link {target}")

    for index_path in sorted(KNOWLEDGE_DIR.rglob("index.md")):
        rel = index_path.relative_to(KNOWLEDGE_DIR).as_posix()
        body = _read_text(index_path)
        for match in re.findall(r"\]\(([^)#]+\.md)\)", body):
            if match.startswith("/"):
                target = KNOWLEDGE_DIR / match.lstrip("/")
            else:
                target = (index_path.parent / match).resolve()
            if not target.is_file():
                errors.append(f"{rel}: broken index link {match}")

    if (KNOWLEDGE_DIR / "log.md").exists():
        errors.append("docs/knowledge/log.md is reserved for future decision logs")

    inventory_sync(check=True)
    inventory_md(check=True)

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        _fail(f"docs knowledge check failed ({len(errors)} issue(s))")
    print("docs knowledge check OK")


def audit_legacy() -> None:
    data = load_inventory()
    entries = data.get("entries", [])
    if not isinstance(entries, list):
        _fail("inventory.json entries must be a list")

    discovered = set(discover_inventory_paths())
    inventory_paths = {
        entry["path"]
        for entry in entries
        if isinstance(entry, dict) and isinstance(entry.get("path"), str)
    }
    missing_inventory = sorted(discovered - inventory_paths)
    stale_inventory = sorted(path for path in inventory_paths if path not in discovered)

    unclassified = [
        entry
        for entry in entries
        if isinstance(entry, dict)
        and entry.get("action") == "keep"
        and entry.get("path", "").startswith("docs/")
        and not entry.get("missing")
    ]

    print("legacy documentation audit")
    print(f"- inventory entries: {len(entries)}")
    print(f"- discovered paths: {len(discovered)}")
    print(f"- missing from inventory: {len(missing_inventory)}")
    print(f"- stale inventory only: {len(stale_inventory)}")
    print(f"- docs/ keep entries: {len(unclassified)}")
    if missing_inventory:
        print("  new paths:")
        for path in missing_inventory[:10]:
            print(f"    - {path}")
    if stale_inventory:
        print("  stale paths:")
        for path in stale_inventory[:10]:
            print(f"    - {path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser("inventory-init", help="Create inventory.json")
    init_parser.add_argument("--force", action="store_true")

    subparsers.add_parser("inventory-sync", help="Reconcile inventory paths")
    subparsers.add_parser("inventory-md", help="Regenerate inventory.md")
    subparsers.add_parser("check-bundle", help="Validate knowledge bundle")
    subparsers.add_parser("audit-legacy", help="Report legacy inventory coverage")

    parser.set_defaults(command="check-bundle")
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    command: str = args.command

    dispatch: dict[str, Callable[[], None]] = {
        "inventory-init": lambda: inventory_init(force=args.force),
        "inventory-sync": inventory_sync,
        "inventory-md": inventory_md,
        "check-bundle": check_bundle,
        "audit-legacy": audit_legacy,
    }
    dispatch[command]()


if __name__ == "__main__":
    main()
