#!/usr/bin/env python3
"""Dual-layer knowledge checks, inventory sync, and legacy audit."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import unicodedata
from collections.abc import Callable, Mapping, Sequence
from contextlib import redirect_stderr
from dataclasses import dataclass
from datetime import date, datetime
from io import StringIO
from pathlib import Path, PurePosixPath
from typing import Any, Literal, NoReturn, cast
from urllib.parse import unquote, urlsplit

import yaml
from pydantic import BaseModel, ConfigDict

ROOT = Path(__file__).resolve().parents[1]
KNOWLEDGE_DIR = ROOT / "docs" / "knowledge"
INVENTORY_JSON = KNOWLEDGE_DIR / "inventory.json"
INVENTORY_MD = KNOWLEDGE_DIR / "inventory.md"
PROFILE_MD = KNOWLEDGE_DIR / "profile.md"

GENERATED_BANNER = "<!-- generated by scripts/docs_knowledge_check.py — do not edit -->"

DOC_TYPES: frozenset[str] = frozenset(
    {
        "Product Overview",
        "Guide",
        "Architecture",
        "Specification",
        "Reference",
        "Runbook",
        "Decision",
        "Roadmap",
        "Audit",
        "Release Note",
        "Archive",
    }
)

INVENTORY_SCHEMA_VERSION = 2
OKF_SPEC_VERSION = "0.2"
MATRYCA_PROFILE_VERSION = "1.0"
DOCS_VALIDATOR_VERSION = "1"
FINDING_SCHEMA_VERSION = "1"
OKF_VERSION = OKF_SPEC_VERSION
REPORT_KIND = "matryca.docs.validation-report"
SOURCE_PATH = "docs/knowledge"
DEFAULT_SOURCE_REPOSITORY = "github.com/MarcoPorcellato/matryca-plumber"
OKF_STATUSES: frozenset[str] = frozenset({"draft", "stable", "deprecated"})
CLASSIFICATIONS: frozenset[str] = frozenset({"canonical", "active", "historical", "generated"})

ACTIONS: frozenset[str] = frozenset(
    {"keep", "migrate", "split", "merge", "archive", "artifact", "generated"}
)

SURFACE_CLASSES: frozenset[str] = frozenset(
    {
        "concept-candidate",
        "runtime-contract",
        "repository-entrypoint",
        "generated",
        "artifact",
    }
)

AUDIENCES: frozenset[str] = frozenset({"maintainer", "contributor", "operator", "agent"})

ROOT_SURFACE_PATHS: tuple[str, ...] = (
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "SUPPORT.md",
    "AGENTS.md",
    "llms.txt",
    ".well-known/llms.txt",
    "SYSTEM_PROMPT.md",
    "ROADMAP.md",
    "CHANGELOG.md",
    "PROJECT_DIARY.md",
)

RESERVED_FILENAMES: frozenset[str] = frozenset({"index.md", "log.md"})

CURATED_ENTRY_FIELDS: frozenset[str] = frozenset(
    {
        "path",
        "type",
        "title",
        "description",
        "classification",
        "audience",
        "surface_class",
        "canonical_for",
        "owner",
        "destination",
        "action",
        "supersedes",
        "notes",
        "missing",
    }
)


@dataclass(frozen=True)
class HeuristicDefaults:
    doc_type: str
    action: str
    surface_class: str
    destination: str | None = None


FindingLayer = Literal["official_okf", "matryca_quality"]
FindingValue = str | int | bool | None


@dataclass(frozen=True)
class ValidationFinding:
    layer: FindingLayer
    code: str
    path: str
    pointer: str
    parameters: tuple[tuple[str, FindingValue], ...]
    message: str
    machine_message: str


@dataclass(frozen=True)
class ValidationReport:
    findings: tuple[ValidationFinding, ...]

    @property
    def official_okf_findings(self) -> tuple[ValidationFinding, ...]:
        return tuple(finding for finding in self.findings if finding.layer == "official_okf")

    @property
    def matryca_quality_findings(self) -> tuple[ValidationFinding, ...]:
        return tuple(finding for finding in self.findings if finding.layer == "matryca_quality")

    @property
    def official_okf(self) -> tuple[str, ...]:
        return tuple(finding.message for finding in self.official_okf_findings)

    @property
    def matryca_quality(self) -> tuple[str, ...]:
        return tuple(finding.message for finding in self.matryca_quality_findings)

    @property
    def has_findings(self) -> bool:
        return bool(self.findings)


class _PolicyPayload(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    okf_spec_version: str
    matryca_profile_version: str
    validator_version: str


class _SourcePayload(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    repository: str
    commit: str | None
    path: str
    provenance_state: Literal["clean", "dirty", "unavailable"]


class _LayerSummaryPayload(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    status: Literal["pass", "fail"]
    finding_count: int


class _SummaryPayload(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    status: Literal["pass", "fail"]
    official_okf: _LayerSummaryPayload
    matryca_quality: _LayerSummaryPayload


class _FindingPayload(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    fingerprint: str
    layer: FindingLayer
    code: str
    path: str
    pointer: str
    parameters: dict[str, FindingValue]
    message: str


class _MachineReportPayload(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["matryca.docs.validation-report"]
    finding_schema_version: str
    policy: _PolicyPayload
    source: _SourcePayload
    summary: _SummaryPayload
    findings: tuple[_FindingPayload, ...]


def _fail(message: str) -> NoReturn:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def _repo_rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _normalize_text(value: str) -> str:
    return unicodedata.normalize("NFC", value)


def _validate_repo_relative_path(path: str) -> str:
    normalized = _normalize_text(path.replace("\\", "/"))
    candidate = PurePosixPath(normalized)
    if candidate.is_absolute() or not normalized or ".." in candidate.parts:
        msg = f"finding path must be repository-relative: {path!r}"
        raise ValueError(msg)
    return candidate.as_posix()


def _finding_path(path: Path, fallback: str) -> str:
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return _validate_repo_relative_path(fallback)


def _finding(
    *,
    layer: FindingLayer,
    code: str,
    path: str,
    message: str,
    machine_message: str | None = None,
    pointer: str = "",
    parameters: Mapping[str, FindingValue] | None = None,
) -> ValidationFinding:
    normalized_parameters: list[tuple[str, FindingValue]] = []
    for key, value in (parameters or {}).items():
        normalized_key = _normalize_text(str(key))
        if isinstance(value, str):
            digest = (
                value
                if normalized_key.endswith("_sha256") and re.fullmatch(r"[0-9a-f]{64}", value)
                else _text_digest(value)
            )
            normalized_value: FindingValue = f"sha256:{digest}"
        else:
            normalized_value = value
        normalized_parameters.append((normalized_key, normalized_value))
    return ValidationFinding(
        layer=layer,
        code=_normalize_text(code),
        path=_validate_repo_relative_path(path),
        pointer=_normalize_text(pointer),
        parameters=tuple(sorted(normalized_parameters)),
        message=_normalize_text(message),
        machine_message=_normalize_text(machine_message or f"validation failed: {code}"),
    )


def _append_error(
    errors: list[str],
    findings: list[ValidationFinding] | None,
    *,
    layer: FindingLayer,
    code: str,
    path: str,
    message: str,
    machine_message: str | None = None,
    pointer: str = "",
    parameters: Mapping[str, FindingValue] | None = None,
) -> None:
    errors.append(message)
    if findings is not None:
        findings.append(
            _finding(
                layer=layer,
                code=code,
                path=path,
                pointer=pointer,
                parameters=parameters,
                message=message,
                machine_message=machine_message,
            )
        )


def _canonical_json(payload: Mapping[str, Any]) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def _text_digest(value: str) -> str:
    return hashlib.sha256(_normalize_text(value).encode("utf-8")).hexdigest()


def _policy_payload() -> _PolicyPayload:
    return _PolicyPayload(
        okf_spec_version=OKF_SPEC_VERSION,
        matryca_profile_version=MATRYCA_PROFILE_VERSION,
        validator_version=DOCS_VALIDATOR_VERSION,
    )


def _finding_fingerprint(finding: ValidationFinding, policy: _PolicyPayload) -> str:
    identity = {
        "finding_schema_version": FINDING_SCHEMA_VERSION,
        "policy": policy.model_dump(mode="json"),
        "layer": finding.layer,
        "code": finding.code,
        "path": finding.path,
        "pointer": finding.pointer,
        "parameters": dict(finding.parameters),
    }
    digest = hashlib.sha256(_canonical_json(identity).encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def _finding_sort_key(finding: ValidationFinding) -> tuple[int, str, str, str, str]:
    return (
        0 if finding.layer == "official_okf" else 1,
        finding.path,
        finding.code,
        finding.pointer,
        _canonical_json(dict(finding.parameters)),
    )


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        msg = "missing YAML frontmatter opener"
        raise ValueError(msg)
    end = text.find("\n---\n", 4)
    if end == -1:
        msg = "missing YAML frontmatter closer"
        raise ValueError(msg)
    raw = text[4:end]
    body = text[end + 5 :]
    data = yaml.safe_load(raw)
    if not isinstance(data, dict):
        msg = "frontmatter must be a mapping"
        raise ValueError(msg)
    return data, body


def split_frontmatter(path: Path) -> tuple[dict[str, Any] | None, str]:
    text = _read_text(path)
    if not text.startswith("---\n"):
        return None, text
    try:
        meta, body = parse_frontmatter(text)
    except (ValueError, yaml.YAMLError):
        return None, text
    return meta, body


def _first_heading_title(text: str) -> str | None:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def _first_sentence(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("```"):
            continue
        sentence = re.split(r"(?<=[.!?])\s+", stripped, maxsplit=1)[0].strip()
        if sentence:
            return sentence
    return ""


def _default_owner(path: str) -> str:
    if path.startswith("docs/openspec/agent"):
        return "prompt-runtime"
    if path.startswith("docs/roadmaps/"):
        return "planning"
    if path.startswith("docs/releases/"):
        return "release"
    if path.startswith("docs/quality/"):
        return "quality"
    return "core-runtime"


def _heuristic_defaults(path: str) -> HeuristicDefaults:
    if path in ROOT_SURFACE_PATHS:
        if path in {"SYSTEM_PROMPT.md", "llms.txt", ".well-known/llms.txt"}:
            return HeuristicDefaults(
                "Reference",
                "generated",
                "generated",
                None,
            )
        if path == "CHANGELOG.md":
            return HeuristicDefaults(
                "Release Note",
                "generated",
                "generated",
                None,
            )
        if path == "PROJECT_DIARY.md":
            return HeuristicDefaults(
                "Decision",
                "split",
                "repository-entrypoint",
                "docs/knowledge/decisions/",
            )
        return HeuristicDefaults(
            "Reference",
            "keep",
            "repository-entrypoint",
            None,
        )
    if path.startswith("docs/releases/"):
        return HeuristicDefaults(
            "Release Note",
            "archive",
            "concept-candidate",
            "docs/knowledge/releases/",
        )
    if path.startswith("docs/quality/issue-bodies/"):
        return HeuristicDefaults("Archive", "artifact", "artifact", "docs/artifacts/issue-bodies/")
    if path.startswith("docs/roadmaps/"):
        return HeuristicDefaults(
            "Roadmap",
            "migrate",
            "concept-candidate",
            "docs/knowledge/roadmaps/active/",
        )
    if path.startswith("docs/openspec/"):
        return HeuristicDefaults(
            "Specification",
            "migrate",
            "concept-candidate",
            "docs/knowledge/specifications/",
        )
    if path.startswith("docs/v1.8-"):
        return HeuristicDefaults("Archive", "archive", "concept-candidate", "docs/archive/plans/")
    if path.startswith("docs/AUDIT_"):
        return HeuristicDefaults(
            "Audit",
            "archive",
            "concept-candidate",
            "docs/knowledge/quality/audits/",
        )
    if path == "docs/ARCHITECTURE.md":
        return HeuristicDefaults(
            "Architecture",
            "split",
            "concept-candidate",
            "docs/knowledge/architecture/",
        )
    if path == "docs/PROJECT_DIARY.md":
        return HeuristicDefaults(
            "Decision",
            "split",
            "concept-candidate",
            "docs/knowledge/decisions/",
        )
    if path.startswith("docs/quality/"):
        return HeuristicDefaults("Audit", "archive", "concept-candidate", "docs/knowledge/quality/")
    if path.startswith("docs/integrations/"):
        return HeuristicDefaults("Guide", "migrate", "concept-candidate", "docs/knowledge/guides/")
    return HeuristicDefaults("Archive", "keep", "concept-candidate", None)


def _default_audience(path: str) -> list[str]:
    if path in {"llms.txt", ".well-known/llms.txt", "SYSTEM_PROMPT.md"}:
        return ["agent", "operator"]
    if path in {"README.md", "CONTRIBUTING.md"}:
        return ["contributor", "operator"]
    if path.startswith("docs/openspec/agent"):
        return ["agent", "maintainer"]
    return ["maintainer", "contributor"]


def _default_classification(path: str, action: str) -> str:
    if action == "generated":
        return "generated"
    if action in {"artifact", "archive"}:
        return "historical"
    if path in ROOT_SURFACE_PATHS:
        return "canonical"
    return "active"


def discover_inventory_paths() -> list[str]:
    paths: set[str] = set(ROOT_SURFACE_PATHS)
    docs_root = ROOT / "docs"
    for path in sorted(docs_root.rglob("*.md")):
        rel = _repo_rel(path)
        if rel.startswith("docs/knowledge/"):
            continue
        paths.add(rel)
    return sorted(paths)


def build_default_entry(path: str) -> dict[str, Any]:
    file_path = ROOT / path
    text = _read_text(file_path) if file_path.is_file() else ""
    title = _first_heading_title(text) or path
    description = _first_sentence(text) or f"Documentation file at {path}."
    defaults = _heuristic_defaults(path)
    classification = _default_classification(path, defaults.action)
    entry: dict[str, Any] = {
        "path": path,
        "type": defaults.doc_type,
        "title": title,
        "description": description,
        "classification": classification,
        "audience": _default_audience(path),
        "surface_class": defaults.surface_class,
        "canonical_for": None,
        "owner": _default_owner(path),
        "destination": defaults.destination,
        "action": defaults.action,
        "supersedes": [],
        "notes": "",
    }
    if path == "docs/ARCHITECTURE.md":
        entry["canonical_for"] = "architecture.system"
    return entry


def load_inventory() -> dict[str, Any]:
    if not INVENTORY_JSON.is_file():
        _fail(f"missing inventory: {INVENTORY_JSON.relative_to(ROOT)}")
    parsed: object = json.loads(_read_text(INVENTORY_JSON))
    if not isinstance(parsed, dict):
        _fail("inventory.json root must be an object")
    return cast(dict[str, Any], parsed)


def validate_inventory_schema(
    data: Mapping[str, Any],
    *,
    findings: list[ValidationFinding] | None = None,
) -> list[str]:
    errors: list[str] = []
    inventory_path = "docs/knowledge/inventory.json"

    def add(
        code: str,
        message: str,
        *,
        pointer: str = "",
        parameters: Mapping[str, FindingValue] | None = None,
    ) -> None:
        _append_error(
            errors,
            findings,
            layer="matryca_quality",
            code=code,
            path=inventory_path,
            pointer=pointer,
            parameters=parameters,
            message=message,
        )

    if data.get("schema_version") != INVENTORY_SCHEMA_VERSION:
        add(
            "inventory.schema_version.invalid",
            f"inventory.json schema_version must be {INVENTORY_SCHEMA_VERSION}",
            pointer="schema_version",
            parameters={"expected": INVENTORY_SCHEMA_VERSION},
        )
    if data.get("scope") != "repository-documentation":
        add(
            "inventory.scope.invalid",
            "inventory.json scope must be 'repository-documentation'",
            pointer="scope",
            parameters={"expected": "repository-documentation"},
        )
    entries = data.get("entries")
    if not isinstance(entries, list):
        add("inventory.entries.type", "inventory.json entries must be a list", pointer="entries")
        return errors

    seen_paths: set[str] = set()
    canonical_roles: dict[str, str] = {}
    for index, entry in enumerate(entries):
        prefix = f"entries[{index}]"
        if not isinstance(entry, dict):
            add(
                "inventory.entry.type",
                f"{prefix} must be an object",
                pointer=prefix,
                parameters={"index": index},
            )
            continue
        path = entry.get("path")
        if not isinstance(path, str) or not path:
            add(
                "inventory.entry.path.empty",
                f"{prefix}.path must be a non-empty string",
                pointer=f"{prefix}.path",
                parameters={"index": index},
            )
            continue
        if path in seen_paths:
            add(
                "inventory.entry.path.duplicate",
                f"duplicate inventory path: {path}",
                pointer=f"{prefix}.path",
                parameters={"path": path},
            )
        seen_paths.add(path)
        for field in (
            "type",
            "title",
            "description",
            "classification",
            "action",
            "surface_class",
        ):
            if field not in entry:
                add(
                    "inventory.entry.field.missing",
                    f"{prefix}.{field} is required",
                    pointer=f"{prefix}.{field}",
                    parameters={"field": field, "path": path},
                )
        doc_type = entry.get("type")
        if isinstance(doc_type, str) and doc_type not in DOC_TYPES:
            add(
                "inventory.entry.type.invalid",
                f"{prefix}.type invalid: {doc_type}",
                pointer=f"{prefix}.type",
                parameters={"path": path, "value": doc_type},
            )
        classification = entry.get("classification")
        if isinstance(classification, str) and classification not in CLASSIFICATIONS:
            add(
                "inventory.entry.classification.invalid",
                f"{prefix}.classification invalid: {classification}",
                pointer=f"{prefix}.classification",
                parameters={"path": path, "value": classification},
            )
        action = entry.get("action")
        if isinstance(action, str) and action not in ACTIONS:
            add(
                "inventory.entry.action.invalid",
                f"{prefix}.action invalid: {action}",
                pointer=f"{prefix}.action",
                parameters={"path": path, "value": action},
            )
        surface_class = entry.get("surface_class")
        if isinstance(surface_class, str) and surface_class not in SURFACE_CLASSES:
            add(
                "inventory.entry.surface_class.invalid",
                f"{prefix}.surface_class invalid: {surface_class}",
                pointer=f"{prefix}.surface_class",
                parameters={"path": path, "value": surface_class},
            )
        audience = entry.get("audience")
        if audience is not None and (
            not isinstance(audience, list)
            or not all(isinstance(item, str) and item in AUDIENCES for item in audience)
        ):
            add(
                "inventory.entry.audience.invalid",
                f"{prefix}.audience must be a list of known audience values",
                pointer=f"{prefix}.audience",
                parameters={"path": path},
            )
        destination = entry.get("destination")
        if destination is not None and not isinstance(destination, str):
            add(
                "inventory.entry.destination.type",
                f"{prefix}.destination must be a string or null",
                pointer=f"{prefix}.destination",
                parameters={"path": path},
            )
        canonical_for = entry.get("canonical_for")
        if canonical_for is not None and not isinstance(canonical_for, str):
            add(
                "inventory.entry.canonical_for.type",
                f"{prefix}.canonical_for must be a string or null",
                pointer=f"{prefix}.canonical_for",
                parameters={"path": path},
            )
        if classification == "canonical" and not canonical_for:
            add(
                "inventory.entry.canonical_for.required",
                f"{prefix}.classification canonical requires canonical_for",
                pointer=f"{prefix}.canonical_for",
                parameters={"path": path},
            )
        if canonical_for and classification != "canonical":
            add(
                "inventory.entry.classification.canonical_required",
                f"{prefix}.canonical_for requires classification canonical",
                pointer=f"{prefix}.classification",
                parameters={"path": path},
            )
        if isinstance(canonical_for, str) and canonical_for:
            previous = canonical_roles.get(canonical_for)
            if previous is not None:
                add(
                    "inventory.entry.canonical_for.duplicate",
                    f"duplicate inventory canonical_for {canonical_for!r} in {previous} and {path}",
                    pointer=f"{prefix}.canonical_for",
                    parameters={"canonical_for": canonical_for, "path": path, "previous": previous},
                )
            else:
                canonical_roles[canonical_for] = path

    sorted_paths = [
        entry["path"] for entry in entries if isinstance(entry, dict) and "path" in entry
    ]
    if sorted_paths != sorted(sorted_paths):
        add(
            "inventory.entries.unsorted",
            "inventory.json entries must be sorted by path",
            pointer="entries",
        )
    return errors


def migrate_inventory_schema(data: dict[str, Any]) -> bool:
    """Upgrade the legacy inventory lifecycle field to Matryca classification."""
    if data.get("schema_version") != 1:
        return False
    entries = data.get("entries")
    if not isinstance(entries, list):
        _fail("inventory.json entries must be a list")
    legacy_mapping = {
        "archived": "historical",
        "current": "active",
        "planned": "active",
        "deprecated": "historical",
        "experimental": "active",
    }
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        legacy_status = entry.pop("status", None)
        action = entry.get("action")
        if action == "generated":
            classification = "generated"
        elif entry.get("canonical_for"):
            classification = "canonical"
        else:
            classification = legacy_mapping.get(legacy_status, "active")
        entry["classification"] = classification
    data["schema_version"] = INVENTORY_SCHEMA_VERSION
    return True


def inventory_init(*, force: bool = False) -> None:
    if INVENTORY_JSON.exists() and not force:
        _fail(
            f"{INVENTORY_JSON.relative_to(ROOT)} already exists; "
            "use inventory-sync or --force to overwrite"
        )
    entries = [build_default_entry(path) for path in discover_inventory_paths()]
    payload = {
        "schema_version": INVENTORY_SCHEMA_VERSION,
        "scope": "repository-documentation",
        "entries": entries,
    }
    INVENTORY_JSON.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY_JSON.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"inventory initialized: {len(entries)} entries")


def _inventory_path_state(
    data: Mapping[str, Any],
) -> tuple[dict[str, dict[str, Any]], list[str], list[str], list[str]]:
    existing_entries = data.get("entries", [])
    if not isinstance(existing_entries, list):
        return {}, [], [], []
    by_path = {
        entry["path"]: dict(entry)
        for entry in existing_entries
        if isinstance(entry, dict) and isinstance(entry.get("path"), str)
    }
    discovered = discover_inventory_paths()
    discovered_set = set(discovered)
    new_paths = [path for path in discovered if path not in by_path]
    missing_paths = [
        path for path in by_path if path not in discovered_set and not by_path[path].get("missing")
    ]
    return by_path, discovered, new_paths, missing_paths


def _inventory_drift_finding(data: Mapping[str, Any]) -> ValidationFinding | None:
    _, _, new_paths, missing_paths = _inventory_path_state(data)
    if not new_paths and not missing_paths:
        return None
    details: list[str] = []
    if new_paths:
        details.append(f"new paths ({len(new_paths)}): {', '.join(new_paths[:5])}")
    if missing_paths:
        details.append(f"missing paths ({len(missing_paths)}): {', '.join(missing_paths[:5])}")
    message = "inventory drift detected; run make docs-inventory-sync — " + "; ".join(details)
    return _finding(
        layer="matryca_quality",
        code="inventory.paths.drift",
        path="docs/knowledge/inventory.json",
        pointer="entries",
        parameters={
            "missing_count": len(missing_paths),
            "missing_sha256": _text_digest("\n".join(sorted(missing_paths))),
            "new_count": len(new_paths),
            "new_sha256": _text_digest("\n".join(sorted(new_paths))),
        },
        message=message,
        machine_message="inventory path set differs from discovered documentation",
    )


def inventory_sync(*, check: bool = False) -> None:
    data = load_inventory()
    migrated = migrate_inventory_schema(data) if not check else False
    existing_entries = data.get("entries", [])
    if not isinstance(existing_entries, list):
        _fail("inventory.json entries must be a list")

    by_path, discovered, new_paths, missing_paths = _inventory_path_state(data)

    if check:
        if finding := _inventory_drift_finding(data):
            _fail(finding.message)
        print("inventory sync OK (no drift)")
        return

    discovered_set = set(discovered)
    for path in discovered:
        if path not in by_path:
            by_path[path] = build_default_entry(path)
        else:
            by_path[path]["missing"] = False

    for path, entry in by_path.items():
        if path not in discovered_set:
            entry["missing"] = True

    merged_entries = [by_path[path] for path in sorted(by_path)]
    data["entries"] = merged_entries
    INVENTORY_JSON.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(
        f"inventory synced: {len(new_paths)} added, {len(missing_paths)} marked missing, "
        f"schema migrated={'yes' if migrated else 'no'}, "
        f"{len(merged_entries)} total"
    )


def render_inventory_md(data: Mapping[str, Any]) -> str:
    entries = data.get("entries", [])
    if not isinstance(entries, list):
        _fail("inventory.json entries must be a list")

    lines = [
        "---",
        "type: Reference",
        "title: Repository documentation inventory",
        "description: Generated view of curated documentation inventory entries.",
        "generated: { by: process:docs-knowledge-inventory, at: '2026-08-06T00:00:00Z' }",
        "verified: { by: human:marco-porcellato, at: '2026-08-06T00:00:00Z' }",
        "last_verified: 2026-08-06",
        "stale_after: 2027-02-02",
        "status: stable",
        "classification: generated",
        "audience: [maintainer, agent]",
        "owner: core-runtime",
        "supersedes: []",
        "related: []",
        "---",
        "",
        GENERATED_BANNER,
        "",
        "# Repository documentation inventory",
        "",
        "Generated from [`inventory.json`](inventory.json). Do not edit this file by hand.",
        "",
    ]

    grouped: dict[str, list[dict[str, Any]]] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        action = str(entry.get("action", "keep"))
        grouped.setdefault(action, []).append(entry)

    for action in sorted(grouped):
        lines.append(f"## {action}")
        lines.append("")
        lines.append("| path | type | classification | destination | canonical_for | missing |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for entry in sorted(grouped[action], key=lambda item: str(item.get("path", ""))):
            path = str(entry.get("path", ""))
            doc_type = str(entry.get("type", ""))
            classification = str(entry.get("classification", ""))
            destination = entry.get("destination") or ""
            canonical_for = entry.get("canonical_for") or ""
            missing = "yes" if entry.get("missing") else ""
            lines.append(
                "| "
                f"`{path}` | {doc_type} | {classification} | {destination} | "
                f"{canonical_for} | {missing} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _inventory_md_finding(data: Mapping[str, Any]) -> ValidationFinding | None:
    if not INVENTORY_MD.is_file():
        return _finding(
            layer="matryca_quality",
            code="inventory.generated_view.missing",
            path="docs/knowledge/inventory.md",
            pointer="",
            message=f"missing generated inventory view: {INVENTORY_MD.relative_to(ROOT)}",
        )
    rendered = render_inventory_md(data)
    try:
        current = _read_text(INVENTORY_MD)
    except (OSError, UnicodeError):
        return _finding(
            layer="matryca_quality",
            code="inventory.generated_view.read_failed",
            path="docs/knowledge/inventory.md",
            pointer="",
            message="inventory.md could not be read",
        )
    if current != rendered:
        return _finding(
            layer="matryca_quality",
            code="inventory.generated_view.drift",
            path="docs/knowledge/inventory.md",
            pointer="",
            message="inventory.md drift; run make docs-inventory-md",
        )
    return None


def inventory_md(*, check: bool = False) -> None:
    data = load_inventory()
    rendered = render_inventory_md(data)
    if check:
        if finding := _inventory_md_finding(data):
            _fail(finding.message)
        print("inventory.md OK")
        return
    INVENTORY_MD.write_text(rendered, encoding="utf-8")
    print(f"wrote {INVENTORY_MD.relative_to(ROOT)}")


def _validate_timestamp(value: Any, label: str) -> list[str]:
    if isinstance(value, datetime):
        return []
    if not isinstance(value, str):
        return [f"{label} must be an ISO 8601 string or datetime"]
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return [f"{label} must be an ISO 8601 timestamp"]
    return []


def _validate_iso_date(value: Any, label: str) -> list[str]:
    if isinstance(value, date) and not isinstance(value, datetime):
        return []
    if not isinstance(value, str):
        return [f"{label} must be an ISO 8601 date"]
    try:
        date.fromisoformat(value)
    except ValueError:
        return [f"{label} must be an ISO 8601 date"]
    return []


def _parse_iso_date(value: Any) -> date | None:
    if isinstance(value, date) and not isinstance(value, datetime):
        return value
    if not isinstance(value, str):
        return None
    try:
        return date.fromisoformat(value)
    except ValueError:
        return None


def _parse_timestamp_date(value: Any) -> date | None:
    if isinstance(value, datetime):
        return value.date()
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).date()
    except ValueError:
        return None


def _validate_actor_event(
    value: Any,
    label: str,
    *,
    allow_many: bool,
    report_path: str,
    pointer: str,
    findings: list[ValidationFinding] | None = None,
) -> list[str]:
    errors: list[str] = []

    def add(
        code: str,
        message: str,
        *,
        event_pointer: str,
        index: int | None = None,
    ) -> None:
        parameters: dict[str, FindingValue] = {}
        if index is not None:
            parameters["index"] = index
        _append_error(
            errors,
            findings,
            layer="official_okf",
            code=code,
            path=report_path,
            pointer=event_pointer,
            parameters=parameters,
            message=message,
        )

    if allow_many and isinstance(value, list) and not value:
        add(
            "trust.events.empty",
            f"{label} must contain at least one verification event",
            event_pointer=pointer,
        )
        return errors
    events = value if allow_many and isinstance(value, list) else [value]
    for index, event in enumerate(events):
        event_label = f"{label}[{index}]" if len(events) > 1 else label
        event_pointer = f"{pointer}[{index}]" if len(events) > 1 else pointer
        if not isinstance(event, dict):
            add(
                "trust.event.type",
                f"{event_label} must be a mapping",
                event_pointer=event_pointer,
                index=index if len(events) > 1 else None,
            )
            continue
        actor = event.get("by")
        if not isinstance(actor, str) or not actor:
            add(
                "trust.event.actor.empty",
                f"{event_label}.by must be a non-empty actor",
                event_pointer=f"{event_pointer}.by",
                index=index if len(events) > 1 else None,
            )
        for message in _validate_timestamp(event.get("at"), f"{event_label}.at"):
            add(
                "trust.event.timestamp.invalid",
                message,
                event_pointer=f"{event_pointer}.at",
                index=index if len(events) > 1 else None,
            )
    return errors


def _markdown_link_targets(text: str) -> list[str]:
    targets: list[str] = []
    fenced = False
    for line in text.splitlines():
        if line.lstrip().startswith(("```", "~~~")):
            fenced = not fenced
            continue
        if fenced:
            continue
        targets.extend(re.findall(r"(?<!!)\[[^]]*\]\(([^)]+)\)", line))
    return targets


def _heading_anchors(text: str) -> set[str]:
    anchors: set[str] = set()
    counts: dict[str, int] = {}
    fenced = False
    for line in text.splitlines():
        if line.lstrip().startswith(("```", "~~~")):
            fenced = not fenced
            continue
        if fenced or not (match := re.match(r"^#{1,6}\s+(.+?)\s*#*\s*$", line)):
            continue
        heading = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", match.group(1))
        slug = re.sub(r"[^\w\- ]", "", heading.lower(), flags=re.UNICODE)
        slug = slug.strip().replace(" ", "-")
        occurrence = counts.get(slug, 0)
        counts[slug] = occurrence + 1
        anchors.add(slug if occurrence == 0 else f"{slug}-{occurrence}")
    return anchors


def resolve_bundle_link(target: str) -> Path:
    clean = target.split("#", 1)[0]
    if not clean.startswith("/"):
        msg = f"bundle link must start with /: {target}"
        raise ValueError(msg)
    return KNOWLEDGE_DIR / clean.lstrip("/")


def validate_document_links(
    path: Path,
    text: str,
    label: str,
    *,
    findings: list[ValidationFinding] | None = None,
) -> list[str]:
    errors: list[str] = []
    root = ROOT.resolve()
    report_path = _finding_path(path, label)

    def add(code: str, message: str, machine_message: str, raw_target: str) -> None:
        _append_error(
            errors,
            findings,
            layer="matryca_quality",
            code=code,
            path=report_path,
            pointer="markdown.links",
            parameters={"target_sha256": _text_digest(raw_target)},
            message=message,
            machine_message=machine_message,
        )

    for raw_target in _markdown_link_targets(text):
        target = raw_target.strip()
        if target.startswith("<") and target.endswith(">"):
            target = target[1:-1]
        parsed = urlsplit(target)
        if parsed.scheme or parsed.netloc:
            continue
        relative = unquote(parsed.path)
        if relative.startswith("/"):
            destination = (KNOWLEDGE_DIR / relative.lstrip("/")).resolve()
        elif relative:
            destination = (path.parent / relative).resolve()
        else:
            destination = path.resolve()
        try:
            destination.relative_to(root)
        except ValueError:
            add(
                "link.local.escape",
                f"{label}: local link escapes repository: {raw_target}",
                "local link escapes repository",
                raw_target,
            )
            continue
        if not destination.exists():
            add(
                "link.local.missing",
                f"{label}: broken local link {raw_target}",
                "broken local link",
                raw_target,
            )
            continue
        anchor = unquote(parsed.fragment)
        if anchor and destination.is_file():
            try:
                anchors = _heading_anchors(_read_text(destination))
            except (OSError, UnicodeError):
                add(
                    "link.local.target_read_failed",
                    f"{label}: local link target could not be read: {raw_target}",
                    "local link target could not be read",
                    raw_target,
                )
                continue
            if anchor not in anchors:
                add(
                    "link.local.anchor_missing",
                    f"{label}: broken local anchor {raw_target}",
                    "broken local anchor",
                    raw_target,
                )
    return errors


def resolve_legacy_source(source: str, concept_path: Path) -> Path:
    if not isinstance(source, str) or not source.strip():
        msg = "legacy_sources entries must be non-empty strings"
        raise ValueError(msg)
    normalized = source.strip()
    if normalized.startswith("/") or Path(normalized).is_absolute():
        msg = f"legacy_sources must be repo-relative paths, not absolute: {source}"
        raise ValueError(msg)
    resolved = (concept_path.parent / normalized).resolve()
    root = ROOT.resolve()
    try:
        resolved.relative_to(root)
    except ValueError as exc:
        msg = f"legacy_sources must resolve inside repository root: {source}"
        raise ValueError(msg) from exc
    return resolved


def validate_legacy_sources(
    meta: Mapping[str, Any],
    concept_path: Path,
    label: str,
    *,
    findings: list[ValidationFinding] | None = None,
) -> list[str]:
    errors: list[str] = []
    report_path = _finding_path(concept_path, label)

    def add(
        code: str,
        message: str,
        *,
        pointer: str = "legacy_sources",
        source: str | None = None,
        index: int | None = None,
        machine_message: str | None = None,
    ) -> None:
        parameters: dict[str, FindingValue] = {}
        if source is not None:
            parameters["source_sha256"] = _text_digest(source)
        if index is not None:
            parameters["index"] = index
        _append_error(
            errors,
            findings,
            layer="matryca_quality",
            code=code,
            path=report_path,
            pointer=pointer,
            parameters=parameters,
            message=message,
            machine_message=machine_message,
        )

    legacy_sources = meta.get("legacy_sources")
    if legacy_sources is None:
        return errors
    if not isinstance(legacy_sources, list):
        add("legacy_sources.type", f"{label}: legacy_sources must be a list")
        return errors
    for index, source in enumerate(legacy_sources):
        if not isinstance(source, str):
            add(
                "legacy_sources.entry.type",
                f"{label}: legacy_sources[{index}] must be a string",
                pointer=f"legacy_sources[{index}]",
                index=index,
            )
            continue
        try:
            resolved = resolve_legacy_source(source, concept_path)
        except ValueError as exc:
            add(
                "legacy_sources.entry.unsafe",
                f"{label}: {exc}",
                pointer=f"legacy_sources[{index}]",
                source=source,
                index=index,
                machine_message="legacy source is not repository-safe",
            )
            continue
        if not resolved.is_file():
            add(
                "legacy_sources.entry.missing",
                f"{label}: missing legacy_sources target {source!r}",
                pointer=f"legacy_sources[{index}]",
                source=source,
                index=index,
                machine_message="missing legacy source target",
            )
    return errors


def validate_official_okf_frontmatter(
    path: Path,
    meta: Mapping[str, Any],
    *,
    findings: list[ValidationFinding] | None = None,
) -> list[str]:
    errors: list[str] = []
    rel = path.relative_to(KNOWLEDGE_DIR).as_posix()
    label = rel
    report_path = _finding_path(path, f"docs/knowledge/{rel}")

    def add(
        code: str,
        message: str,
        *,
        pointer: str,
        parameters: Mapping[str, FindingValue] | None = None,
    ) -> None:
        _append_error(
            errors,
            findings,
            layer="official_okf",
            code=code,
            path=report_path,
            pointer=pointer,
            parameters=parameters,
            message=message,
        )

    doc_type = meta.get("type")
    if not isinstance(doc_type, str) or not doc_type.strip():
        add(
            "frontmatter.type.empty",
            f"{label}: type must be a non-empty string",
            pointer="frontmatter.type",
        )

    status = meta.get("status")
    if status is not None and (not isinstance(status, str) or status not in OKF_STATUSES):
        add(
            "frontmatter.status.invalid",
            f"{label}: invalid OKF status",
            pointer="frontmatter.status",
        )

    if "generated" in meta:
        errors.extend(
            _validate_actor_event(
                meta.get("generated"),
                f"{label}.generated",
                allow_many=False,
                report_path=report_path,
                pointer="frontmatter.generated",
                findings=findings,
            )
        )
    if "verified" in meta:
        errors.extend(
            _validate_actor_event(
                meta.get("verified"),
                f"{label}.verified",
                allow_many=True,
                report_path=report_path,
                pointer="frontmatter.verified",
                findings=findings,
            )
        )
    if "stale_after" in meta:
        for message in _validate_iso_date(meta.get("stale_after"), f"{label}.stale_after"):
            add(
                "frontmatter.stale_after.invalid",
                message,
                pointer="frontmatter.stale_after",
            )
    return errors


def validate_matryca_quality_frontmatter(
    path: Path,
    meta: Mapping[str, Any],
    *,
    findings: list[ValidationFinding] | None = None,
) -> list[str]:
    errors: list[str] = []
    label = path.relative_to(KNOWLEDGE_DIR).as_posix()
    report_path = _finding_path(path, f"docs/knowledge/{label}")

    def add(
        code: str,
        message: str,
        *,
        pointer: str,
        parameters: Mapping[str, FindingValue] | None = None,
    ) -> None:
        _append_error(
            errors,
            findings,
            layer="matryca_quality",
            code=code,
            path=report_path,
            pointer=pointer,
            parameters=parameters,
            message=message,
        )

    for field in (
        "title",
        "description",
        "status",
        "classification",
        "verified",
        "last_verified",
        "stale_after",
    ):
        if field not in meta:
            add(
                "frontmatter.field.missing",
                f"{label}: missing required field {field}",
                pointer=f"frontmatter.{field}",
                parameters={"field": field},
            )

    classification = meta.get("classification")
    if classification is not None and (
        not isinstance(classification, str) or classification not in CLASSIFICATIONS
    ):
        add(
            "frontmatter.classification.invalid",
            f"{label}: invalid Matryca classification",
            pointer="frontmatter.classification",
        )
    canonical_for = meta.get("canonical_for")
    if classification == "canonical" and (not isinstance(canonical_for, str) or not canonical_for):
        add(
            "frontmatter.canonical_for.required",
            f"{label}: canonical concepts require canonical_for",
            pointer="frontmatter.canonical_for",
        )
    if classification == "generated" and "generated" not in meta:
        add(
            "frontmatter.generated.required",
            f"{label}: generated concepts require generated provenance",
            pointer="frontmatter.generated",
        )

    audience = meta.get("audience")
    if audience is not None and (
        not isinstance(audience, list)
        or not all(isinstance(item, str) and item in AUDIENCES for item in audience)
    ):
        add(
            "frontmatter.audience.invalid",
            f"{label}: invalid audience",
            pointer="frontmatter.audience",
        )

    for message in _validate_iso_date(meta.get("last_verified"), f"{label}.last_verified"):
        add(
            "frontmatter.last_verified.invalid",
            message,
            pointer="frontmatter.last_verified",
        )
    last_verified = meta.get("last_verified")
    stale_after = meta.get("stale_after")
    last_verified_date = _parse_iso_date(last_verified)
    stale_after_date = _parse_iso_date(stale_after)
    if (
        last_verified_date is not None
        and stale_after_date is not None
        and stale_after_date <= last_verified_date
    ):
        add(
            "frontmatter.stale_after.order",
            f"{label}: stale_after must be after last_verified",
            pointer="frontmatter.stale_after",
        )

    verified = meta.get("verified")
    events = verified if isinstance(verified, list) else [verified]
    verified_dates = [
        parsed
        for event in events
        if isinstance(event, dict)
        if (parsed := _parse_timestamp_date(event.get("at"))) is not None
    ]
    if verified_dates and last_verified_date is not None:
        expected = max(verified_dates)
        if last_verified_date != expected:
            add(
                "frontmatter.last_verified.mismatch",
                f"{label}: last_verified must match the latest verified event date",
                pointer="frontmatter.last_verified",
            )
    return errors


def validate_concept_frontmatter(path: Path, meta: Mapping[str, Any]) -> list[str]:
    """Return the combined findings for compatibility with existing callers."""
    return validate_official_okf_frontmatter(path, meta) + validate_matryca_quality_frontmatter(
        path, meta
    )


def collect_knowledge_concepts() -> list[Path]:
    concepts: list[Path] = []
    for path in sorted(KNOWLEDGE_DIR.rglob("*.md")):
        if path.name in RESERVED_FILENAMES:
            continue
        concepts.append(path)
    return concepts


def _report_frontmatter(
    path: Path,
    report_path: str,
    findings: list[ValidationFinding],
) -> tuple[dict[str, Any] | None, str] | None:
    try:
        return split_frontmatter(path)
    except (OSError, UnicodeError):
        findings.append(
            _finding(
                layer="official_okf",
                code="document.read.failed",
                path=report_path,
                pointer="",
                message=f"{report_path}: document could not be read",
            )
        )
        return None


def _validation_report(findings: Sequence[ValidationFinding]) -> ValidationReport:
    return ValidationReport(findings=tuple(sorted(findings, key=_finding_sort_key)))


def _print_validation_report(report: ValidationReport) -> None:
    print(
        f"OKF v{OKF_SPEC_VERSION} format compatibility: "
        f"{'FAIL' if report.official_okf else 'PASS'} "
        f"({len(report.official_okf)} findings)"
    )
    print(
        f"Matryca quality profile v{MATRYCA_PROFILE_VERSION}: "
        f"{'FAIL' if report.matryca_quality else 'PASS'} "
        f"({len(report.matryca_quality)} findings)"
    )
    print(f"Validator v{DOCS_VALIDATOR_VERSION}; finding schema v{FINDING_SCHEMA_VERSION}")


def _load_inventory_for_report() -> tuple[dict[str, Any] | None, ValidationFinding | None]:
    stderr = StringIO()
    try:
        with redirect_stderr(stderr):
            return load_inventory(), None
    except (OSError, ValueError, SystemExit) as exc:
        detail = next(
            (line for line in stderr.getvalue().splitlines() if line),
            str(exc) or "inventory load failed",
        )
        return None, _finding(
            layer="matryca_quality",
            code="inventory.load.failed",
            path="docs/knowledge/inventory.json",
            pointer="",
            message=detail,
            machine_message="inventory could not be loaded",
        )


def _normalized_repository(remote: str) -> str | None:
    candidate = remote.strip()
    if not candidate:
        return None
    if "://" in candidate:
        parsed = urlsplit(candidate)
        host = parsed.hostname
        path = parsed.path.strip("/")
    elif match := re.fullmatch(r"(?:[^@]+@)?([^:]+):(.+)", candidate):
        host, path = match.group(1), match.group(2).strip("/")
    else:
        return None
    if not host or not path:
        return None
    if path.endswith(".git"):
        path = path[:-4]
    parts = path.split("/")
    if len(parts) != 2 or not all(re.fullmatch(r"[A-Za-z0-9_.-]+", part) for part in parts):
        return None
    if not re.fullmatch(r"[A-Za-z0-9.-]+", host):
        return None
    return f"{host.lower()}/{parts[0]}/{parts[1]}"


def _git_output(*args: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _source_payload() -> _SourcePayload:
    commit = _git_output("rev-parse", "HEAD")
    if commit is not None and not re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", commit):
        commit = None
    status = _git_output("status", "--porcelain")
    if commit is None or status is None:
        provenance_state: Literal["clean", "dirty", "unavailable"] = "unavailable"
    else:
        provenance_state = "dirty" if status else "clean"
    repository = _normalized_repository(_git_output("remote", "get-url", "origin") or "")
    return _SourcePayload(
        repository=repository or DEFAULT_SOURCE_REPOSITORY,
        commit=commit,
        path=SOURCE_PATH,
        provenance_state=provenance_state,
    )


def _build_machine_report(
    report: ValidationReport,
    *,
    source: _SourcePayload,
    policy: _PolicyPayload | None = None,
) -> _MachineReportPayload:
    active_policy = policy or _policy_payload()
    official_count = len(report.official_okf_findings)
    matryca_count = len(report.matryca_quality_findings)
    status: Literal["pass", "fail"] = "fail" if report.has_findings else "pass"
    findings = tuple(
        _FindingPayload(
            fingerprint=_finding_fingerprint(finding, active_policy),
            layer=finding.layer,
            code=finding.code,
            path=finding.path,
            pointer=finding.pointer,
            parameters=dict(finding.parameters),
            message=finding.machine_message,
        )
        for finding in report.findings
    )
    return _MachineReportPayload(
        kind="matryca.docs.validation-report",
        finding_schema_version=FINDING_SCHEMA_VERSION,
        policy=active_policy,
        source=source,
        summary=_SummaryPayload(
            status=status,
            official_okf=_LayerSummaryPayload(
                status="fail" if official_count else "pass",
                finding_count=official_count,
            ),
            matryca_quality=_LayerSummaryPayload(
                status="fail" if matryca_count else "pass",
                finding_count=matryca_count,
            ),
        ),
        findings=findings,
    )


def _render_machine_report(payload: _MachineReportPayload) -> str:
    return (
        json.dumps(
            payload.model_dump(mode="json"),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def _check_bundle_report() -> ValidationReport:
    findings: list[ValidationFinding] = []

    if not PROFILE_MD.is_file():
        findings.append(
            _finding(
                layer="matryca_quality",
                code="profile.missing",
                path="docs/knowledge/profile.md",
                message="missing docs/knowledge/profile.md",
            )
        )

    data, load_finding = _load_inventory_for_report()
    if load_finding is not None:
        findings.append(load_finding)
    if data is None:
        return _validation_report(findings)
    validate_inventory_schema(data, findings=findings)

    entries = data.get("entries", [])
    canonical_for_values = {
        str(entry["canonical_for"]): f"inventory:{entry['path']}"
        for entry in entries
        if isinstance(entry, dict)
        and isinstance(entry.get("canonical_for"), str)
        and entry.get("canonical_for")
        and isinstance(entry.get("path"), str)
    }
    for concept_path in collect_knowledge_concepts():
        rel = concept_path.relative_to(KNOWLEDGE_DIR).as_posix()
        parsed = _report_frontmatter(
            concept_path,
            _finding_path(concept_path, f"docs/knowledge/{rel}"),
            findings,
        )
        if parsed is None:
            continue
        meta, body = parsed
        if meta is None:
            findings.append(
                _finding(
                    layer="official_okf",
                    code="frontmatter.missing",
                    path=_finding_path(concept_path, f"docs/knowledge/{rel}"),
                    pointer="frontmatter",
                    message=f"{rel}: concept documents require YAML frontmatter",
                )
            )
            continue
        validate_official_okf_frontmatter(concept_path, meta, findings=findings)
        validate_matryca_quality_frontmatter(concept_path, meta, findings=findings)
        validate_legacy_sources(meta, concept_path, rel, findings=findings)

        canonical_for = meta.get("canonical_for")
        if canonical_for is not None:
            if not isinstance(canonical_for, str):
                findings.append(
                    _finding(
                        layer="matryca_quality",
                        code="canonical_for.type.invalid",
                        path=_finding_path(concept_path, f"docs/knowledge/{rel}"),
                        pointer="frontmatter.canonical_for",
                        message=f"{rel}: canonical_for must be a string",
                    )
                )
            elif canonical_for in canonical_for_values:
                findings.append(
                    _finding(
                        layer="matryca_quality",
                        code="canonical_for.duplicate",
                        path=_finding_path(concept_path, f"docs/knowledge/{rel}"),
                        pointer="frontmatter.canonical_for",
                        parameters={"canonical_for": canonical_for},
                        message=(
                            f"duplicate canonical_for {canonical_for!r} in "
                            f"{canonical_for_values[canonical_for]} and {rel}"
                        ),
                    )
                )
            else:
                canonical_for_values[canonical_for] = rel

        validate_document_links(concept_path, body, rel, findings=findings)

    for index_path in sorted(KNOWLEDGE_DIR.rglob("index.md")):
        rel = index_path.relative_to(KNOWLEDGE_DIR).as_posix()
        parsed = _report_frontmatter(
            index_path,
            _finding_path(index_path, f"docs/knowledge/{rel}"),
            findings,
        )
        if parsed is None:
            continue
        meta, body = parsed
        if index_path == KNOWLEDGE_DIR / "index.md":
            if meta is not None and meta.get("okf_version") != OKF_VERSION:
                findings.append(
                    _finding(
                        layer="official_okf",
                        code="index.root.frontmatter.invalid",
                        path=_finding_path(index_path, f"docs/knowledge/{rel}"),
                        pointer="frontmatter",
                        parameters={"expected_okf_version": OKF_VERSION},
                        message=f"{rel}: root index frontmatter must declare okf_version: {OKF_VERSION!r}",
                    )
                )
        elif meta is not None:
            findings.append(
                _finding(
                    layer="official_okf",
                    code="index.nested.frontmatter.present",
                    path=_finding_path(index_path, f"docs/knowledge/{rel}"),
                    pointer="frontmatter",
                    message=f"{rel}: nested OKF indexes must not have frontmatter",
                )
            )
        validate_document_links(index_path, body, rel, findings=findings)

    log_path = KNOWLEDGE_DIR / "log.md"
    if not log_path.is_file():
        findings.append(
            _finding(
                layer="official_okf",
                code="log.missing",
                path="docs/knowledge/log.md",
                message="missing docs/knowledge/log.md",
            )
        )
    else:
        parsed = _report_frontmatter(log_path, "docs/knowledge/log.md", findings)
        if parsed is None:
            return _validation_report(findings)
        meta, body = parsed
        if meta is not None:
            findings.append(
                _finding(
                    layer="official_okf",
                    code="log.frontmatter.present",
                    path="docs/knowledge/log.md",
                    pointer="frontmatter",
                    message="log.md: OKF log files must not have frontmatter",
                )
            )
        date_headings = re.findall(r"^## (\d{4}-\d{2}-\d{2})$", body, re.MULTILINE)
        if not date_headings:
            findings.append(
                _finding(
                    layer="matryca_quality",
                    code="log.date_heading.missing",
                    path="docs/knowledge/log.md",
                    pointer="markdown.headings",
                    message="log.md: expected at least one ISO date heading",
                )
            )
        elif date_headings != sorted(date_headings, reverse=True):
            findings.append(
                _finding(
                    layer="matryca_quality",
                    code="log.date_heading.order",
                    path="docs/knowledge/log.md",
                    pointer="markdown.headings",
                    message="log.md: date headings must be newest first",
                )
            )
        validate_document_links(log_path, body, "log.md", findings=findings)

    if drift_finding := _inventory_drift_finding(data):
        findings.append(drift_finding)
    if generated_finding := _inventory_md_finding(data):
        findings.append(generated_finding)

    return _validation_report(findings)


def check_bundle(*, output_format: Literal["text", "json"] = "text") -> None:
    report = _check_bundle_report()
    if output_format == "json":
        sys.stdout.write(
            _render_machine_report(_build_machine_report(report, source=_source_payload()))
        )
        if report.has_findings:
            raise SystemExit(1)
        return

    if not any(finding.code == "inventory.paths.drift" for finding in report.findings):
        print("inventory sync OK (no drift)")
    if not any(finding.code.startswith("inventory.generated_view.") for finding in report.findings):
        print("inventory.md OK")
    _print_validation_report(report)
    if report.has_findings:
        for error in report.official_okf:
            print(f"[official-okf] {error}", file=sys.stderr)
        for error in report.matryca_quality:
            print(f"[matryca-quality] {error}", file=sys.stderr)
        total = len(report.official_okf) + len(report.matryca_quality)
        _fail(f"docs knowledge check failed ({total} issue(s))")
    print("docs knowledge check OK")


def audit_legacy() -> None:
    data = load_inventory()
    entries = data.get("entries", [])
    if not isinstance(entries, list):
        _fail("inventory.json entries must be a list")

    discovered = set(discover_inventory_paths())
    inventory_paths = {
        entry["path"]
        for entry in entries
        if isinstance(entry, dict) and isinstance(entry.get("path"), str)
    }
    missing_inventory = sorted(discovered - inventory_paths)
    stale_inventory = sorted(path for path in inventory_paths if path not in discovered)

    unclassified = [
        entry
        for entry in entries
        if isinstance(entry, dict)
        and entry.get("action") == "keep"
        and entry.get("path", "").startswith("docs/")
        and not entry.get("missing")
    ]

    print("legacy documentation audit")
    print(f"- inventory entries: {len(entries)}")
    print(f"- discovered paths: {len(discovered)}")
    print(f"- missing from inventory: {len(missing_inventory)}")
    print(f"- stale inventory only: {len(stale_inventory)}")
    print(f"- docs/ keep entries: {len(unclassified)}")
    if missing_inventory:
        print("  new paths:")
        for path in missing_inventory[:10]:
            print(f"    - {path}")
    if stale_inventory:
        print("  stale paths:")
        for path in stale_inventory[:10]:
            print(f"    - {path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser("inventory-init", help="Create inventory.json")
    init_parser.add_argument("--force", action="store_true")

    subparsers.add_parser("inventory-sync", help="Reconcile inventory paths")
    subparsers.add_parser("inventory-md", help="Regenerate inventory.md")
    check_parser = subparsers.add_parser("check-bundle", help="Validate knowledge bundle")
    check_parser.add_argument("--format", choices=("text", "json"), default="text")
    subparsers.add_parser("audit-legacy", help="Report legacy inventory coverage")

    parser.set_defaults(command="check-bundle")
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    command: str = args.command

    dispatch: dict[str, Callable[[], None]] = {
        "inventory-init": lambda: inventory_init(force=args.force),
        "inventory-sync": inventory_sync,
        "inventory-md": inventory_md,
        "check-bundle": lambda: check_bundle(output_format=args.format),
        "audit-legacy": audit_legacy,
    }
    dispatch[command]()


if __name__ == "__main__":
    main()
