#!/usr/bin/env python3
"""Dual-layer knowledge checks, inventory sync, and legacy audit."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Callable, Mapping, Sequence
from contextlib import redirect_stderr
from dataclasses import dataclass
from datetime import date, datetime
from io import StringIO
from pathlib import Path
from typing import Any, NoReturn, cast
from urllib.parse import unquote, urlsplit

import yaml

ROOT = Path(__file__).resolve().parents[1]
KNOWLEDGE_DIR = ROOT / "docs" / "knowledge"
INVENTORY_JSON = KNOWLEDGE_DIR / "inventory.json"
INVENTORY_MD = KNOWLEDGE_DIR / "inventory.md"
PROFILE_MD = KNOWLEDGE_DIR / "profile.md"

GENERATED_BANNER = "<!-- generated by scripts/docs_knowledge_check.py — do not edit -->"

DOC_TYPES: frozenset[str] = frozenset(
    {
        "Product Overview",
        "Guide",
        "Architecture",
        "Specification",
        "Reference",
        "Runbook",
        "Decision",
        "Roadmap",
        "Audit",
        "Release Note",
        "Archive",
    }
)

INVENTORY_SCHEMA_VERSION = 2
OKF_SPEC_VERSION = "0.2"
MATRYCA_PROFILE_VERSION = "1.0"
DOCS_VALIDATOR_VERSION = "1"
FINDING_SCHEMA_VERSION = "1"
OKF_VERSION = OKF_SPEC_VERSION
OKF_STATUSES: frozenset[str] = frozenset({"draft", "stable", "deprecated"})
CLASSIFICATIONS: frozenset[str] = frozenset({"canonical", "active", "historical", "generated"})

ACTIONS: frozenset[str] = frozenset(
    {"keep", "migrate", "split", "merge", "archive", "artifact", "generated"}
)

SURFACE_CLASSES: frozenset[str] = frozenset(
    {
        "concept-candidate",
        "runtime-contract",
        "repository-entrypoint",
        "generated",
        "artifact",
    }
)

AUDIENCES: frozenset[str] = frozenset({"maintainer", "contributor", "operator", "agent"})

ROOT_SURFACE_PATHS: tuple[str, ...] = (
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "SUPPORT.md",
    "AGENTS.md",
    "llms.txt",
    ".well-known/llms.txt",
    "SYSTEM_PROMPT.md",
    "ROADMAP.md",
    "CHANGELOG.md",
    "PROJECT_DIARY.md",
)

RESERVED_FILENAMES: frozenset[str] = frozenset({"index.md", "log.md"})

CURATED_ENTRY_FIELDS: frozenset[str] = frozenset(
    {
        "path",
        "type",
        "title",
        "description",
        "classification",
        "audience",
        "surface_class",
        "canonical_for",
        "owner",
        "destination",
        "action",
        "supersedes",
        "notes",
        "missing",
    }
)


@dataclass(frozen=True)
class HeuristicDefaults:
    doc_type: str
    action: str
    surface_class: str
    destination: str | None = None


@dataclass(frozen=True)
class ValidationReport:
    official_okf: tuple[str, ...]
    matryca_quality: tuple[str, ...]

    @property
    def has_findings(self) -> bool:
        return bool(self.official_okf or self.matryca_quality)


def _fail(message: str) -> NoReturn:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def _repo_rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        msg = "missing YAML frontmatter opener"
        raise ValueError(msg)
    end = text.find("\n---\n", 4)
    if end == -1:
        msg = "missing YAML frontmatter closer"
        raise ValueError(msg)
    raw = text[4:end]
    body = text[end + 5 :]
    data = yaml.safe_load(raw)
    if not isinstance(data, dict):
        msg = "frontmatter must be a mapping"
        raise ValueError(msg)
    return data, body


def split_frontmatter(path: Path) -> tuple[dict[str, Any] | None, str]:
    text = _read_text(path)
    if not text.startswith("---\n"):
        return None, text
    try:
        meta, body = parse_frontmatter(text)
    except ValueError:
        return None, text
    return meta, body


def _first_heading_title(text: str) -> str | None:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def _first_sentence(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("```"):
            continue
        sentence = re.split(r"(?<=[.!?])\s+", stripped, maxsplit=1)[0].strip()
        if sentence:
            return sentence
    return ""


def _default_owner(path: str) -> str:
    if path.startswith("docs/openspec/agent"):
        return "prompt-runtime"
    if path.startswith("docs/roadmaps/"):
        return "planning"
    if path.startswith("docs/releases/"):
        return "release"
    if path.startswith("docs/quality/"):
        return "quality"
    return "core-runtime"


def _heuristic_defaults(path: str) -> HeuristicDefaults:
    if path in ROOT_SURFACE_PATHS:
        if path in {"SYSTEM_PROMPT.md", "llms.txt", ".well-known/llms.txt"}:
            return HeuristicDefaults(
                "Reference",
                "generated",
                "generated",
                None,
            )
        if path == "CHANGELOG.md":
            return HeuristicDefaults(
                "Release Note",
                "generated",
                "generated",
                None,
            )
        if path == "PROJECT_DIARY.md":
            return HeuristicDefaults(
                "Decision",
                "split",
                "repository-entrypoint",
                "docs/knowledge/decisions/",
            )
        return HeuristicDefaults(
            "Reference",
            "keep",
            "repository-entrypoint",
            None,
        )
    if path.startswith("docs/releases/"):
        return HeuristicDefaults(
            "Release Note",
            "archive",
            "concept-candidate",
            "docs/knowledge/releases/",
        )
    if path.startswith("docs/quality/issue-bodies/"):
        return HeuristicDefaults("Archive", "artifact", "artifact", "docs/artifacts/issue-bodies/")
    if path.startswith("docs/roadmaps/"):
        return HeuristicDefaults(
            "Roadmap",
            "migrate",
            "concept-candidate",
            "docs/knowledge/roadmaps/active/",
        )
    if path.startswith("docs/openspec/"):
        return HeuristicDefaults(
            "Specification",
            "migrate",
            "concept-candidate",
            "docs/knowledge/specifications/",
        )
    if path.startswith("docs/v1.8-"):
        return HeuristicDefaults("Archive", "archive", "concept-candidate", "docs/archive/plans/")
    if path.startswith("docs/AUDIT_"):
        return HeuristicDefaults(
            "Audit",
            "archive",
            "concept-candidate",
            "docs/knowledge/quality/audits/",
        )
    if path == "docs/ARCHITECTURE.md":
        return HeuristicDefaults(
            "Architecture",
            "split",
            "concept-candidate",
            "docs/knowledge/architecture/",
        )
    if path == "docs/PROJECT_DIARY.md":
        return HeuristicDefaults(
            "Decision",
            "split",
            "concept-candidate",
            "docs/knowledge/decisions/",
        )
    if path.startswith("docs/quality/"):
        return HeuristicDefaults("Audit", "archive", "concept-candidate", "docs/knowledge/quality/")
    if path.startswith("docs/integrations/"):
        return HeuristicDefaults("Guide", "migrate", "concept-candidate", "docs/knowledge/guides/")
    return HeuristicDefaults("Archive", "keep", "concept-candidate", None)


def _default_audience(path: str) -> list[str]:
    if path in {"llms.txt", ".well-known/llms.txt", "SYSTEM_PROMPT.md"}:
        return ["agent", "operator"]
    if path in {"README.md", "CONTRIBUTING.md"}:
        return ["contributor", "operator"]
    if path.startswith("docs/openspec/agent"):
        return ["agent", "maintainer"]
    return ["maintainer", "contributor"]


def _default_classification(path: str, action: str) -> str:
    if action == "generated":
        return "generated"
    if action in {"artifact", "archive"}:
        return "historical"
    if path in ROOT_SURFACE_PATHS:
        return "canonical"
    return "active"


def discover_inventory_paths() -> list[str]:
    paths: set[str] = set(ROOT_SURFACE_PATHS)
    docs_root = ROOT / "docs"
    for path in sorted(docs_root.rglob("*.md")):
        rel = _repo_rel(path)
        if rel.startswith("docs/knowledge/"):
            continue
        paths.add(rel)
    return sorted(paths)


def build_default_entry(path: str) -> dict[str, Any]:
    file_path = ROOT / path
    text = _read_text(file_path) if file_path.is_file() else ""
    title = _first_heading_title(text) or path
    description = _first_sentence(text) or f"Documentation file at {path}."
    defaults = _heuristic_defaults(path)
    classification = _default_classification(path, defaults.action)
    entry: dict[str, Any] = {
        "path": path,
        "type": defaults.doc_type,
        "title": title,
        "description": description,
        "classification": classification,
        "audience": _default_audience(path),
        "surface_class": defaults.surface_class,
        "canonical_for": None,
        "owner": _default_owner(path),
        "destination": defaults.destination,
        "action": defaults.action,
        "supersedes": [],
        "notes": "",
    }
    if path == "docs/ARCHITECTURE.md":
        entry["canonical_for"] = "architecture.system"
    return entry


def load_inventory() -> dict[str, Any]:
    if not INVENTORY_JSON.is_file():
        _fail(f"missing inventory: {INVENTORY_JSON.relative_to(ROOT)}")
    parsed: object = json.loads(_read_text(INVENTORY_JSON))
    if not isinstance(parsed, dict):
        _fail("inventory.json root must be an object")
    return cast(dict[str, Any], parsed)


def validate_inventory_schema(data: Mapping[str, Any]) -> list[str]:
    errors: list[str] = []
    if data.get("schema_version") != INVENTORY_SCHEMA_VERSION:
        errors.append(f"inventory.json schema_version must be {INVENTORY_SCHEMA_VERSION}")
    if data.get("scope") != "repository-documentation":
        errors.append("inventory.json scope must be 'repository-documentation'")
    entries = data.get("entries")
    if not isinstance(entries, list):
        errors.append("inventory.json entries must be a list")
        return errors

    seen_paths: set[str] = set()
    canonical_roles: dict[str, str] = {}
    for index, entry in enumerate(entries):
        prefix = f"entries[{index}]"
        if not isinstance(entry, dict):
            errors.append(f"{prefix} must be an object")
            continue
        path = entry.get("path")
        if not isinstance(path, str) or not path:
            errors.append(f"{prefix}.path must be a non-empty string")
            continue
        if path in seen_paths:
            errors.append(f"duplicate inventory path: {path}")
        seen_paths.add(path)
        for field in (
            "type",
            "title",
            "description",
            "classification",
            "action",
            "surface_class",
        ):
            if field not in entry:
                errors.append(f"{prefix}.{field} is required")
        doc_type = entry.get("type")
        if isinstance(doc_type, str) and doc_type not in DOC_TYPES:
            errors.append(f"{prefix}.type invalid: {doc_type}")
        classification = entry.get("classification")
        if isinstance(classification, str) and classification not in CLASSIFICATIONS:
            errors.append(f"{prefix}.classification invalid: {classification}")
        action = entry.get("action")
        if isinstance(action, str) and action not in ACTIONS:
            errors.append(f"{prefix}.action invalid: {action}")
        surface_class = entry.get("surface_class")
        if isinstance(surface_class, str) and surface_class not in SURFACE_CLASSES:
            errors.append(f"{prefix}.surface_class invalid: {surface_class}")
        audience = entry.get("audience")
        if audience is not None and (
            not isinstance(audience, list)
            or not all(isinstance(item, str) and item in AUDIENCES for item in audience)
        ):
            errors.append(f"{prefix}.audience must be a list of known audience values")
        destination = entry.get("destination")
        if destination is not None and not isinstance(destination, str):
            errors.append(f"{prefix}.destination must be a string or null")
        canonical_for = entry.get("canonical_for")
        if canonical_for is not None and not isinstance(canonical_for, str):
            errors.append(f"{prefix}.canonical_for must be a string or null")
        if classification == "canonical" and not canonical_for:
            errors.append(f"{prefix}.classification canonical requires canonical_for")
        if canonical_for and classification != "canonical":
            errors.append(f"{prefix}.canonical_for requires classification canonical")
        if isinstance(canonical_for, str) and canonical_for:
            previous = canonical_roles.get(canonical_for)
            if previous is not None:
                errors.append(
                    f"duplicate inventory canonical_for {canonical_for!r} in {previous} and {path}"
                )
            else:
                canonical_roles[canonical_for] = path

    sorted_paths = [
        entry["path"] for entry in entries if isinstance(entry, dict) and "path" in entry
    ]
    if sorted_paths != sorted(sorted_paths):
        errors.append("inventory.json entries must be sorted by path")
    return errors


def migrate_inventory_schema(data: dict[str, Any]) -> bool:
    """Upgrade the legacy inventory lifecycle field to Matryca classification."""
    if data.get("schema_version") != 1:
        return False
    entries = data.get("entries")
    if not isinstance(entries, list):
        _fail("inventory.json entries must be a list")
    legacy_mapping = {
        "archived": "historical",
        "current": "active",
        "planned": "active",
        "deprecated": "historical",
        "experimental": "active",
    }
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        legacy_status = entry.pop("status", None)
        action = entry.get("action")
        if action == "generated":
            classification = "generated"
        elif entry.get("canonical_for"):
            classification = "canonical"
        else:
            classification = legacy_mapping.get(legacy_status, "active")
        entry["classification"] = classification
    data["schema_version"] = INVENTORY_SCHEMA_VERSION
    return True


def inventory_init(*, force: bool = False) -> None:
    if INVENTORY_JSON.exists() and not force:
        _fail(
            f"{INVENTORY_JSON.relative_to(ROOT)} already exists; "
            "use inventory-sync or --force to overwrite"
        )
    entries = [build_default_entry(path) for path in discover_inventory_paths()]
    payload = {
        "schema_version": INVENTORY_SCHEMA_VERSION,
        "scope": "repository-documentation",
        "entries": entries,
    }
    INVENTORY_JSON.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY_JSON.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"inventory initialized: {len(entries)} entries")


def inventory_sync(*, check: bool = False) -> None:
    data = load_inventory()
    migrated = migrate_inventory_schema(data) if not check else False
    existing_entries = data.get("entries", [])
    if not isinstance(existing_entries, list):
        _fail("inventory.json entries must be a list")

    by_path: dict[str, dict[str, Any]] = {}
    for entry in existing_entries:
        if isinstance(entry, dict) and isinstance(entry.get("path"), str):
            by_path[entry["path"]] = dict(entry)

    discovered = discover_inventory_paths()
    discovered_set = set(discovered)
    new_paths = [path for path in discovered if path not in by_path]
    missing_paths = [
        path for path in by_path if path not in discovered_set and not by_path[path].get("missing")
    ]

    if check:
        if new_paths or missing_paths:
            details: list[str] = []
            if new_paths:
                details.append(f"new paths ({len(new_paths)}): {', '.join(new_paths[:5])}")
            if missing_paths:
                details.append(
                    f"missing paths ({len(missing_paths)}): {', '.join(missing_paths[:5])}"
                )
            _fail("inventory drift detected; run make docs-inventory-sync — " + "; ".join(details))
        print("inventory sync OK (no drift)")
        return

    for path in discovered:
        if path not in by_path:
            by_path[path] = build_default_entry(path)
        else:
            by_path[path]["missing"] = False

    for path, entry in by_path.items():
        if path not in discovered_set:
            entry["missing"] = True

    merged_entries = [by_path[path] for path in sorted(by_path)]
    data["entries"] = merged_entries
    INVENTORY_JSON.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(
        f"inventory synced: {len(new_paths)} added, {len(missing_paths)} marked missing, "
        f"schema migrated={'yes' if migrated else 'no'}, "
        f"{len(merged_entries)} total"
    )


def render_inventory_md(data: Mapping[str, Any]) -> str:
    entries = data.get("entries", [])
    if not isinstance(entries, list):
        _fail("inventory.json entries must be a list")

    lines = [
        "---",
        "type: Reference",
        "title: Repository documentation inventory",
        "description: Generated view of curated documentation inventory entries.",
        "generated: { by: process:docs-knowledge-inventory, at: '2026-08-06T00:00:00Z' }",
        "verified: { by: human:marco-porcellato, at: '2026-08-06T00:00:00Z' }",
        "last_verified: 2026-08-06",
        "stale_after: 2027-02-02",
        "status: stable",
        "classification: generated",
        "audience: [maintainer, agent]",
        "owner: core-runtime",
        "supersedes: []",
        "related: []",
        "---",
        "",
        GENERATED_BANNER,
        "",
        "# Repository documentation inventory",
        "",
        "Generated from [`inventory.json`](inventory.json). Do not edit this file by hand.",
        "",
    ]

    grouped: dict[str, list[dict[str, Any]]] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        action = str(entry.get("action", "keep"))
        grouped.setdefault(action, []).append(entry)

    for action in sorted(grouped):
        lines.append(f"## {action}")
        lines.append("")
        lines.append("| path | type | classification | destination | canonical_for | missing |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for entry in sorted(grouped[action], key=lambda item: str(item.get("path", ""))):
            path = str(entry.get("path", ""))
            doc_type = str(entry.get("type", ""))
            classification = str(entry.get("classification", ""))
            destination = entry.get("destination") or ""
            canonical_for = entry.get("canonical_for") or ""
            missing = "yes" if entry.get("missing") else ""
            lines.append(
                "| "
                f"`{path}` | {doc_type} | {classification} | {destination} | "
                f"{canonical_for} | {missing} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def inventory_md(*, check: bool = False) -> None:
    data = load_inventory()
    rendered = render_inventory_md(data)
    if check:
        if not INVENTORY_MD.is_file():
            _fail(f"missing generated inventory view: {INVENTORY_MD.relative_to(ROOT)}")
        if _read_text(INVENTORY_MD) != rendered:
            _fail("inventory.md drift; run make docs-inventory-md")
        print("inventory.md OK")
        return
    INVENTORY_MD.write_text(rendered, encoding="utf-8")
    print(f"wrote {INVENTORY_MD.relative_to(ROOT)}")


def _validate_timestamp(value: Any, label: str) -> list[str]:
    if isinstance(value, datetime):
        return []
    if not isinstance(value, str):
        return [f"{label} must be an ISO 8601 string or datetime"]
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return [f"{label} must be an ISO 8601 timestamp"]
    return []


def _validate_iso_date(value: Any, label: str) -> list[str]:
    if isinstance(value, date) and not isinstance(value, datetime):
        return []
    if not isinstance(value, str):
        return [f"{label} must be an ISO 8601 date"]
    try:
        date.fromisoformat(value)
    except ValueError:
        return [f"{label} must be an ISO 8601 date"]
    return []


def _parse_iso_date(value: Any) -> date | None:
    if isinstance(value, date) and not isinstance(value, datetime):
        return value
    if not isinstance(value, str):
        return None
    try:
        return date.fromisoformat(value)
    except ValueError:
        return None


def _parse_timestamp_date(value: Any) -> date | None:
    if isinstance(value, datetime):
        return value.date()
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).date()
    except ValueError:
        return None


def _validate_actor_event(value: Any, label: str, *, allow_many: bool) -> list[str]:
    if allow_many and isinstance(value, list) and not value:
        return [f"{label} must contain at least one verification event"]
    events = value if allow_many and isinstance(value, list) else [value]
    errors: list[str] = []
    for index, event in enumerate(events):
        event_label = f"{label}[{index}]" if len(events) > 1 else label
        if not isinstance(event, dict):
            errors.append(f"{event_label} must be a mapping")
            continue
        actor = event.get("by")
        if not isinstance(actor, str) or not actor:
            errors.append(f"{event_label}.by must be a non-empty actor")
        errors.extend(_validate_timestamp(event.get("at"), f"{event_label}.at"))
    return errors


def _markdown_link_targets(text: str) -> list[str]:
    targets: list[str] = []
    fenced = False
    for line in text.splitlines():
        if line.lstrip().startswith(("```", "~~~")):
            fenced = not fenced
            continue
        if fenced:
            continue
        targets.extend(re.findall(r"(?<!!)\[[^]]*\]\(([^)]+)\)", line))
    return targets


def _heading_anchors(text: str) -> set[str]:
    anchors: set[str] = set()
    counts: dict[str, int] = {}
    fenced = False
    for line in text.splitlines():
        if line.lstrip().startswith(("```", "~~~")):
            fenced = not fenced
            continue
        if fenced or not (match := re.match(r"^#{1,6}\s+(.+?)\s*#*\s*$", line)):
            continue
        heading = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", match.group(1))
        slug = re.sub(r"[^\w\- ]", "", heading.lower(), flags=re.UNICODE)
        slug = slug.strip().replace(" ", "-")
        occurrence = counts.get(slug, 0)
        counts[slug] = occurrence + 1
        anchors.add(slug if occurrence == 0 else f"{slug}-{occurrence}")
    return anchors


def resolve_bundle_link(target: str) -> Path:
    clean = target.split("#", 1)[0]
    if not clean.startswith("/"):
        msg = f"bundle link must start with /: {target}"
        raise ValueError(msg)
    return KNOWLEDGE_DIR / clean.lstrip("/")


def validate_document_links(path: Path, text: str, label: str) -> list[str]:
    errors: list[str] = []
    root = ROOT.resolve()
    for raw_target in _markdown_link_targets(text):
        target = raw_target.strip()
        if target.startswith("<") and target.endswith(">"):
            target = target[1:-1]
        parsed = urlsplit(target)
        if parsed.scheme or parsed.netloc:
            continue
        relative = unquote(parsed.path)
        if relative.startswith("/"):
            destination = (KNOWLEDGE_DIR / relative.lstrip("/")).resolve()
        elif relative:
            destination = (path.parent / relative).resolve()
        else:
            destination = path.resolve()
        try:
            destination.relative_to(root)
        except ValueError:
            errors.append(f"{label}: local link escapes repository: {raw_target}")
            continue
        if not destination.exists():
            errors.append(f"{label}: broken local link {raw_target}")
            continue
        anchor = unquote(parsed.fragment)
        if anchor and destination.is_file():
            anchors = _heading_anchors(_read_text(destination))
            if anchor not in anchors:
                errors.append(f"{label}: broken local anchor {raw_target}")
    return errors


def resolve_legacy_source(source: str, concept_path: Path) -> Path:
    if not isinstance(source, str) or not source.strip():
        msg = "legacy_sources entries must be non-empty strings"
        raise ValueError(msg)
    normalized = source.strip()
    if normalized.startswith("/") or Path(normalized).is_absolute():
        msg = f"legacy_sources must be repo-relative paths, not absolute: {source}"
        raise ValueError(msg)
    resolved = (concept_path.parent / normalized).resolve()
    root = ROOT.resolve()
    try:
        resolved.relative_to(root)
    except ValueError as exc:
        msg = f"legacy_sources must resolve inside repository root: {source}"
        raise ValueError(msg) from exc
    return resolved


def validate_legacy_sources(
    meta: Mapping[str, Any],
    concept_path: Path,
    label: str,
) -> list[str]:
    errors: list[str] = []
    legacy_sources = meta.get("legacy_sources")
    if legacy_sources is None:
        return errors
    if not isinstance(legacy_sources, list):
        errors.append(f"{label}: legacy_sources must be a list")
        return errors
    for index, source in enumerate(legacy_sources):
        if not isinstance(source, str):
            errors.append(f"{label}: legacy_sources[{index}] must be a string")
            continue
        try:
            resolved = resolve_legacy_source(source, concept_path)
        except ValueError as exc:
            errors.append(f"{label}: {exc}")
            continue
        if not resolved.is_file():
            errors.append(f"{label}: missing legacy_sources target {source!r}")
    return errors


def validate_official_okf_frontmatter(path: Path, meta: Mapping[str, Any]) -> list[str]:
    errors: list[str] = []
    rel = path.relative_to(KNOWLEDGE_DIR).as_posix()
    label = rel

    doc_type = meta.get("type")
    if not isinstance(doc_type, str) or not doc_type.strip():
        errors.append(f"{label}: type must be a non-empty string")

    status = meta.get("status")
    if status is not None and (not isinstance(status, str) or status not in OKF_STATUSES):
        errors.append(f"{label}: invalid OKF status")

    if "generated" in meta:
        errors.extend(
            _validate_actor_event(meta.get("generated"), f"{label}.generated", allow_many=False)
        )
    if "verified" in meta:
        errors.extend(
            _validate_actor_event(meta.get("verified"), f"{label}.verified", allow_many=True)
        )
    if "stale_after" in meta:
        errors.extend(_validate_iso_date(meta.get("stale_after"), f"{label}.stale_after"))
    return errors


def validate_matryca_quality_frontmatter(path: Path, meta: Mapping[str, Any]) -> list[str]:
    errors: list[str] = []
    label = path.relative_to(KNOWLEDGE_DIR).as_posix()

    for field in (
        "title",
        "description",
        "status",
        "classification",
        "verified",
        "last_verified",
        "stale_after",
    ):
        if field not in meta:
            errors.append(f"{label}: missing required field {field}")

    classification = meta.get("classification")
    if classification is not None and (
        not isinstance(classification, str) or classification not in CLASSIFICATIONS
    ):
        errors.append(f"{label}: invalid Matryca classification")
    canonical_for = meta.get("canonical_for")
    if classification == "canonical" and (not isinstance(canonical_for, str) or not canonical_for):
        errors.append(f"{label}: canonical concepts require canonical_for")
    if classification == "generated" and "generated" not in meta:
        errors.append(f"{label}: generated concepts require generated provenance")

    audience = meta.get("audience")
    if audience is not None and (
        not isinstance(audience, list)
        or not all(isinstance(item, str) and item in AUDIENCES for item in audience)
    ):
        errors.append(f"{label}: invalid audience")

    errors.extend(_validate_iso_date(meta.get("last_verified"), f"{label}.last_verified"))
    last_verified = meta.get("last_verified")
    stale_after = meta.get("stale_after")
    last_verified_date = _parse_iso_date(last_verified)
    stale_after_date = _parse_iso_date(stale_after)
    if (
        last_verified_date is not None
        and stale_after_date is not None
        and stale_after_date <= last_verified_date
    ):
        errors.append(f"{label}: stale_after must be after last_verified")

    verified = meta.get("verified")
    events = verified if isinstance(verified, list) else [verified]
    verified_dates = [
        parsed
        for event in events
        if isinstance(event, dict)
        if (parsed := _parse_timestamp_date(event.get("at"))) is not None
    ]
    if verified_dates and last_verified_date is not None:
        expected = max(verified_dates)
        if last_verified_date != expected:
            errors.append(f"{label}: last_verified must match the latest verified event date")
    return errors


def validate_concept_frontmatter(path: Path, meta: Mapping[str, Any]) -> list[str]:
    """Return the combined findings for compatibility with existing callers."""
    return validate_official_okf_frontmatter(path, meta) + validate_matryca_quality_frontmatter(
        path, meta
    )


def collect_knowledge_concepts() -> list[Path]:
    concepts: list[Path] = []
    for path in sorted(KNOWLEDGE_DIR.rglob("*.md")):
        if path.name in RESERVED_FILENAMES:
            continue
        concepts.append(path)
    return concepts


def _validation_report(
    official_okf: list[str],
    matryca_quality: list[str],
) -> ValidationReport:
    return ValidationReport(
        official_okf=tuple(sorted(official_okf)),
        matryca_quality=tuple(sorted(matryca_quality)),
    )


def _print_validation_report(report: ValidationReport) -> None:
    print(
        f"OKF v{OKF_SPEC_VERSION} format compatibility: "
        f"{'FAIL' if report.official_okf else 'PASS'} "
        f"({len(report.official_okf)} findings)"
    )
    print(
        f"Matryca quality profile v{MATRYCA_PROFILE_VERSION}: "
        f"{'FAIL' if report.matryca_quality else 'PASS'} "
        f"({len(report.matryca_quality)} findings)"
    )
    print(f"Validator v{DOCS_VALIDATOR_VERSION}; finding schema v{FINDING_SCHEMA_VERSION}")


def _collect_check_failures(check: Callable[[], None]) -> list[str]:
    stderr = StringIO()
    try:
        with redirect_stderr(stderr):
            check()
    except SystemExit:
        findings = [line for line in stderr.getvalue().splitlines() if line]
        return findings or ["validation command failed without a diagnostic"]
    return []


def check_bundle() -> None:
    official_okf: list[str] = []
    matryca_quality: list[str] = []

    if not PROFILE_MD.is_file():
        matryca_quality.append("missing docs/knowledge/profile.md")

    data = load_inventory()
    matryca_quality.extend(validate_inventory_schema(data))

    entries = data.get("entries", [])
    canonical_for_values = {
        str(entry["canonical_for"]): f"inventory:{entry['path']}"
        for entry in entries
        if isinstance(entry, dict)
        and isinstance(entry.get("canonical_for"), str)
        and entry.get("canonical_for")
        and isinstance(entry.get("path"), str)
    }
    for concept_path in collect_knowledge_concepts():
        rel = concept_path.relative_to(KNOWLEDGE_DIR).as_posix()
        meta, body = split_frontmatter(concept_path)
        if meta is None:
            official_okf.append(f"{rel}: concept documents require YAML frontmatter")
            continue
        official_okf.extend(validate_official_okf_frontmatter(concept_path, meta))
        matryca_quality.extend(validate_matryca_quality_frontmatter(concept_path, meta))
        matryca_quality.extend(validate_legacy_sources(meta, concept_path, rel))

        canonical_for = meta.get("canonical_for")
        if canonical_for is not None:
            if not isinstance(canonical_for, str):
                matryca_quality.append(f"{rel}: canonical_for must be a string")
            elif canonical_for in canonical_for_values:
                matryca_quality.append(
                    f"duplicate canonical_for {canonical_for!r} in "
                    f"{canonical_for_values[canonical_for]} and {rel}"
                )
            else:
                canonical_for_values[canonical_for] = rel

        matryca_quality.extend(validate_document_links(concept_path, body, rel))

    for index_path in sorted(KNOWLEDGE_DIR.rglob("index.md")):
        rel = index_path.relative_to(KNOWLEDGE_DIR).as_posix()
        meta, body = split_frontmatter(index_path)
        if index_path == KNOWLEDGE_DIR / "index.md":
            if meta != {"okf_version": OKF_VERSION}:
                official_okf.append(
                    f"{rel}: root index frontmatter must contain only okf_version: {OKF_VERSION!r}"
                )
        elif meta is not None:
            official_okf.append(f"{rel}: nested OKF indexes must not have frontmatter")
        matryca_quality.extend(validate_document_links(index_path, body, rel))

    log_path = KNOWLEDGE_DIR / "log.md"
    if not log_path.is_file():
        official_okf.append("missing docs/knowledge/log.md")
    else:
        meta, body = split_frontmatter(log_path)
        if meta is not None:
            official_okf.append("log.md: OKF log files must not have frontmatter")
        date_headings = re.findall(r"^## (\d{4}-\d{2}-\d{2})$", body, re.MULTILINE)
        if not date_headings:
            matryca_quality.append("log.md: expected at least one ISO date heading")
        elif date_headings != sorted(date_headings, reverse=True):
            matryca_quality.append("log.md: date headings must be newest first")
        matryca_quality.extend(validate_document_links(log_path, body, "log.md"))

    matryca_quality.extend(_collect_check_failures(lambda: inventory_sync(check=True)))
    matryca_quality.extend(_collect_check_failures(lambda: inventory_md(check=True)))

    report = _validation_report(official_okf, matryca_quality)
    _print_validation_report(report)
    if report.has_findings:
        for error in report.official_okf:
            print(f"[official-okf] {error}", file=sys.stderr)
        for error in report.matryca_quality:
            print(f"[matryca-quality] {error}", file=sys.stderr)
        total = len(report.official_okf) + len(report.matryca_quality)
        _fail(f"docs knowledge check failed ({total} issue(s))")
    print("docs knowledge check OK")


def audit_legacy() -> None:
    data = load_inventory()
    entries = data.get("entries", [])
    if not isinstance(entries, list):
        _fail("inventory.json entries must be a list")

    discovered = set(discover_inventory_paths())
    inventory_paths = {
        entry["path"]
        for entry in entries
        if isinstance(entry, dict) and isinstance(entry.get("path"), str)
    }
    missing_inventory = sorted(discovered - inventory_paths)
    stale_inventory = sorted(path for path in inventory_paths if path not in discovered)

    unclassified = [
        entry
        for entry in entries
        if isinstance(entry, dict)
        and entry.get("action") == "keep"
        and entry.get("path", "").startswith("docs/")
        and not entry.get("missing")
    ]

    print("legacy documentation audit")
    print(f"- inventory entries: {len(entries)}")
    print(f"- discovered paths: {len(discovered)}")
    print(f"- missing from inventory: {len(missing_inventory)}")
    print(f"- stale inventory only: {len(stale_inventory)}")
    print(f"- docs/ keep entries: {len(unclassified)}")
    if missing_inventory:
        print("  new paths:")
        for path in missing_inventory[:10]:
            print(f"    - {path}")
    if stale_inventory:
        print("  stale paths:")
        for path in stale_inventory[:10]:
            print(f"    - {path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser("inventory-init", help="Create inventory.json")
    init_parser.add_argument("--force", action="store_true")

    subparsers.add_parser("inventory-sync", help="Reconcile inventory paths")
    subparsers.add_parser("inventory-md", help="Regenerate inventory.md")
    subparsers.add_parser("check-bundle", help="Validate knowledge bundle")
    subparsers.add_parser("audit-legacy", help="Report legacy inventory coverage")

    parser.set_defaults(command="check-bundle")
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    command: str = args.command

    dispatch: dict[str, Callable[[], None]] = {
        "inventory-init": lambda: inventory_init(force=args.force),
        "inventory-sync": inventory_sync,
        "inventory-md": inventory_md,
        "check-bundle": check_bundle,
        "audit-legacy": audit_legacy,
    }
    dispatch[command]()


if __name__ == "__main__":
    main()
